const KEY='studyTracker.v30';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2,10);
const PEN_MODULES=[
['3. Introduction To Cybersecurity','The Practice of Cybersecurity|Threats and Threat Actors|The CIA Triad|Security Principles, Controls, and Strategies|Cybersecurity Laws, Regulations, Standards, and Frameworks|Career Opportunities in Cybersecurity'],
['4. Effective Learning Strategies','Learning Theory|Unique Challenges to Learning Technical Skills|OffSec Training Methodology|Tactics and Common Methods|Advice and Suggestions on Exams|Practical Steps'],
['5. Report Writing for Penetration Testers','Understanding Note-Taking|Writing Effective Technical Penetration Testing Reports'],
['6. Information Gathering','The Penetration Testing Lifecycle|Passive Information Gathering|Active Information Gathering'],
['7. Vulnerability Scanning','Vulnerability Scanning Theory|Vulnerability Scanning with Nessus|Vulnerability Scanning with Nmap'],
['8. Introduction to Web Application Attacks','Web Application Assessment Methodology|Web Application Assessment Tools|Web Application Enumeration|Cross-Site Scripting'],
['9. Common Web Application Attacks','Directory Traversal|File Inclusion Vulnerabilities|File Upload Vulnerabilities|Command Injection'],
['10. SQL Injection Attacks','SQL Theory and Databases|Manual SQL Exploitation|Manual and Automated Code Execution'],
['11. Client-side Attacks','Target Reconnaissance|Exploiting Microsoft Office|Abusing Windows Library Files'],
['12. Antivirus Evasion','Antivirus Software Components and Operations|Bypassing Antivirus Detections|AV Evasion in Practice'],
['13. Password Attacks','Attacking Network Services Logins|Password Cracking Fundamentals|Working with Password Hashes'],
['14. Fixing Exploits','Fixing Memory Corruption Exploits|Fixing Web Exploits'],
['15. Locating Public Exploits','Getting Started|Online Exploit Resources|Offline Exploit Resources|Exploiting a Target'],
['16. Windows Privilege Escalation','Enumerating Windows|Leveraging Windows Services|Abusing Other Windows Components'],
['17. Linux Privilege Escalation','Enumerating Linux|Exposed Confidential Information|Insecure File Permissions|Insecure System Components'],
['18. Port Redirection and SSH Tunneling','Why Port Redirection and Tunneling?|Port Forwarding with Linux Tools|SSH Tunneling|Port Forwarding with Windows Tools'],
['19. Tunneling Through Deep Packet Inspection','HTTP Tunneling Theory and Practice|DNS Tunneling Theory and Practice'],
['20. The Metasploit Framework','Getting Familiar with Metasploit|Using Metasploit Payloads|Performing Post-Exploitation with Metasploit|Automating Metasploit'],
['21. Active Directory Introduction and Enumeration','Active Directory Introduction|Manual Enumeration|Permissions, Users, SPNs and Shares|SharpHound and BloodHound'],
['22. Attacking Active Directory Authentication','NTLM, Kerberos and Cached Credentials|Password Attacks|AS-REP Roasting|Kerberoasting|Silver Tickets|Domain Controller Synchronization'],
['23. Lateral Movement in Active Directory','WMI and WinRM|PsExec|Pass the Hash|Overpass the Hash|Pass the Ticket|DCOM|Golden Ticket and Shadow Copies'],
['24. Assembling the Pieces','Enumerating the Public Network|Attacking a Public Machine|Gaining Access to the Internal Network|Enumerating the Internal Network|Attacking an Internal Web Application']
];
function datePlus(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function penSubject(){const total=PEN_MODULES.reduce((n,x)=>n+x[1].split('|').length,0);let i=0;return {id:'pen200',name:'PEN-200 (2023)',description:'Penetration Testing with Kali Linux — 90-day book plan',color:'#7c5cff',icon:'P2',modules:PEN_MODULES.map(([name,list])=>({id:uid(),name,topics:list.split('|').map(name=>({id:uid(),name,status:'not-started',due:datePlus(Math.min(89,Math.floor(i++*90/total))) }))}))}}
const seed={profile:null,settings:{theme:'dark',sounds:true,notifications:true},subjects:[penSubject()],tasks:[],events:[],jobApplications:[],notes:[{id:uid(),title:'PEN-200 Study Method',subjectId:'pen200',content:'Read, reproduce each technique in your authorized lab, record evidence, then complete exercises before moving on.',updated:today()}],activity:[],activeWorkspace:'primary',workspaces:[{id:'primary',name:'PEN-200 · 90 Days',archived:false}]};
const cloudConfig=window.STUDY_TRACKER_CONFIG||{},sb=cloudConfig.supabaseUrl&&window.supabase?window.supabase.createClient(cloudConfig.supabaseUrl,cloudConfig.supabaseAnonKey):null;
let cloudUser=null,syncTimer=null,state=load(),viewName='dashboard',selectedSubject=state.subjects[0]?.id||'',selectedNote=state.notes[0]?.id,calDate=new Date(),timerSeconds=25*60,timerInitial=25*60,timerHandle=null,jobQuery='',jobFilter='All',jobSort='newest';
function normalizeState(x){const next=Object.assign(structuredClone(seed),x||{});next.jobApplications=Array.isArray(next.jobApplications)?next.jobApplications:[];return next}
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(seed)}}
function save(){if(state?.workspaces?.length&&typeof storeWorkspace==='function')storeWorkspace();localStorage.setItem(KEY,JSON.stringify(state));applyTheme();if(cloudUser&&sb){clearTimeout(syncTimer);syncTimer=setTimeout(syncCloud,450)}}
async function syncCloud(){if(!cloudUser||!sb)return;const payload=structuredClone(state);if(payload.profile)delete payload.profile.pin;const {error}=await sb.from('user_tracker_data').upsert({user_id:cloudUser.id,data:payload},{onConflict:'user_id'});if(error)console.error('Cloud sync failed',error.message)}
async function loadCloud(){const {data,error}=await sb.from('user_tracker_data').select('data').eq('user_id',cloudUser.id).maybeSingle();if(error)throw error;if(data?.data){state=normalizeState(data.data);state.profile=state.profile||{name:cloudUser.user_metadata?.full_name||cloudUser.email.split('@')[0]}}else{state=structuredClone(seed);state.profile={name:cloudUser.user_metadata?.full_name||cloudUser.email.split('@')[0],email:cloudUser.email};await syncCloud()}selectedSubject=state.subjects[0]?.id||'';selectedNote=state.notes[0]?.id;localStorage.setItem(KEY,JSON.stringify(state))}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pct(subject){const t=subject.modules.flatMap(m=>m.topics);return t.length?Math.round(t.filter(x=>x.status==='completed').length/t.length*100):0}
function allTopics(){return state.subjects.flatMap(s=>s.modules.flatMap(m=>m.topics.map(t=>({...t,subjectId:s.id,subject:s.name,module:m.name}))))}
function overall(){const t=allTopics();return t.length?Math.round(t.filter(x=>x.status==='completed').length/t.length*100):0}
function streak(){const days=new Set(state.activity.filter(a=>a.minutes>0).map(a=>a.date));let n=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function subjectName(id){return state.subjects.find(s=>s.id===id)?.name||'General'}
function toast(msg){const x=document.querySelector('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function applyTheme(){document.body.className=state.settings.theme==='dark'?'':`theme-${state.settings.theme}`}
function beep(){if(!state.settings.sounds)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=520;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}
async function login(e){e.preventDefault();const name=loginName.value.trim(),pin=loginPin.value;if(sb&&name.includes('@')){const button=e.submitter;button.disabled=true;button.textContent='Signing in…';let result=await sb.auth.signInWithPassword({email:name,password:pin});if(result.error){result=await sb.auth.signUp({email:name,password:pin,options:{data:{full_name:name.split('@')[0]}}});if(result.error){button.disabled=false;button.innerHTML='Continue <span>→</span>';return toast(result.error.message)}if(!result.data.session){button.disabled=false;button.innerHTML='Continue <span>→</span>';return toast('Check your email to confirm the account')}}cloudUser=result.data.user;await loadCloud();return showApp()}if(state.profile&&state.profile.pin!==pin)return toast('Incorrect local PIN');state.profile={name,pin};save();showApp()}
function showApp(){authScreen.classList.add('hidden');app.classList.remove('hidden');avatar.textContent=(state.profile?.name||'P')[0].toUpperCase();render()}
function head(title,sub,action=''){return `<div class="page-head"><div><span class="eyebrow">STUDY TRACKER</span><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function taskRows(tasks){if(!tasks.length)return '<div class="empty">No tasks here yet.</div>';return `<div class="task-list">${tasks.map(t=>{const overdue=t.due&&t.due<today()&&t.status!=='completed';return `<div class="task-row ${t.status==='completed'?'done':''}"><button class="check ${t.status==='completed'?'checked':''}" onclick="toggleTask('${t.id}')">${t.status==='completed'?'✓':''}</button><div><div class="task-name">${escapeHtml(t.title)}</div><div class="task-meta">${escapeHtml(subjectName(t.subjectId))} · ${t.due||'No date'} ${t.time||''}</div></div><div class="row-actions"><span class="badge ${overdue?'danger':t.priority==='high'?'warn':''}">${overdue?'Overdue':t.priority}</span><button class="mini-btn" title="Edit task" onclick="taskModal('${t.id}')">✎</button><button class="mini-btn" title="Delete task" onclick="deleteTask('${t.id}')">×</button></div></div>`}).join('')}</div>`}
function dashboard(){setTimeout(drawCharts);const p=overall(),due=state.tasks.filter(t=>t.status!=='completed'&&t.due===today()),completed=allTopics().filter(t=>t.status==='completed').length;return head(`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${escapeHtml(state.profile.name.split(' ')[0])}`,"Your study progress and analytics in one place")+`<div class="grid stats"><div class="stat"><div class="stat-icon">◫</div><div><small>Total subjects</small><strong>${state.subjects.length}</strong></div></div><div class="stat"><div class="stat-icon">✓</div><div><small>Topics completed</small><strong>${completed}</strong></div></div><div class="stat"><div class="stat-icon">◷</div><div><small>Due today</small><strong>${due.length}</strong></div></div><div class="stat"><div class="stat-icon">⌁</div><div><small>Study hours</small><strong>${Math.round(state.activity.reduce((a,x)=>a+x.minutes,0)/60)}h</strong></div></div></div><div class="grid dashboard-grid"><section class="card span-2"><div class="card-title"><h3>Overall progress</h3><span>All subjects</span></div><div class="overview-flex"><div class="progress-ring" style="--p:${p}"><div><strong>${p}%</strong><small>completed</small></div></div><div class="subject-bars">${state.subjects.slice(0,5).map(s=>`<div class="bar-row"><span>${escapeHtml(s.name)}</span><div class="bar"><i style="width:${pct(s)}%"></i></div><b>${pct(s)}%</b></div>`).join('')}</div></div></section><section class="card"><div class="card-title"><h3>Subject progress analytics</h3><span>Completion %</span></div><div class="chart-box"><canvas id="progressChart"></canvas></div></section><section class="card"><div class="card-title"><h3>Status distribution</h3><span>${streak()} day streak</span></div><div class="chart-box"><canvas id="statusChart"></canvas></div></section><section class="card span-2"><div class="card-title"><h3>Upcoming deadlines</h3><button class="kebab" onclick="setView('calendar')">Calendar →</button></div>${taskRows(state.tasks.filter(t=>t.status!=='completed').sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,5))}</section></div>`}
function subjects(){return head('My subjects','Manage all your learning tracks','<button class="btn primary" onclick="subjectModal()">+ Add subject</button>')+`<div class="grid subject-grid">${state.subjects.map(s=>`<article class="card subject-card" style="--subject:${s.color}" onclick="openSubject('${s.id}')"><div class="subject-top"><div class="subject-icon">${escapeHtml(s.icon)}</div><button class="kebab" onclick="event.stopPropagation();subjectModal('${s.id}')">•••</button></div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p><div class="progress-line"><i style="width:${pct(s)}%"></i></div><div class="progress-label"><span>${s.modules.length} modules</span><strong>${pct(s)}%</strong></div></article>`).join('')}</div>`}
function subjectView(){const s=state.subjects.find(x=>x.id===selectedSubject)||state.subjects[0];if(!s)return subjects();return head(`${escapeHtml(s.name)} tracker`,escapeHtml(s.description),`<button class="btn primary" onclick="moduleModal('${s.id}')">+ Add module</button>`)+`<div class="grid stats"><div class="stat"><div><small>Overall progress</small><strong>${pct(s)}%</strong></div></div><div class="stat"><div><small>Modules</small><strong>${s.modules.length}</strong></div></div><div class="stat"><div><small>Topics</small><strong>${s.modules.flatMap(m=>m.topics).length}</strong></div></div><div class="stat"><div><small>Completed</small><strong>${s.modules.flatMap(m=>m.topics).filter(t=>t.status==='completed').length}</strong></div></div></div><div class="grid">${s.modules.map((m,i)=>`<section class="card module"><div class="module-head"><h3>${i+1}. ${escapeHtml(m.name)}</h3><button class="btn ghost" onclick="topicModal('${s.id}','${m.id}')">+ Topic</button></div><div class="module-body">${m.topics.length?m.topics.map(t=>`<div class="subtopic-row"><button class="check ${t.status==='completed'?'checked':''}" onclick="cycleTopic('${s.id}','${m.id}','${t.id}')">${t.status==='completed'?'✓':''}</button><span>${escapeHtml(t.name)}</span><select onchange="topicStatus('${s.id}','${m.id}','${t.id}',this.value)"><option value="not-started" ${t.status==='not-started'?'selected':''}>Not started</option><option value="in-progress" ${t.status==='in-progress'?'selected':''}>In progress</option><option value="completed" ${t.status==='completed'?'selected':''}>Completed</option></select><input type="date" value="${t.due||''}" onchange="topicDue('${s.id}','${m.id}','${t.id}',this.value)"><button class="kebab" onclick="deleteTopic('${s.id}','${m.id}','${t.id}')">×</button></div>`).join(''):'<div class="empty">No topics in this module.</div>'}</div></section>`).join('')}</div>`}
function todayView(){const due=state.tasks.filter(t=>t.due===today());return head('Today plan',new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}),'<button class="btn primary" onclick="taskModal()">+ New task</button>')+`<section class="card">${taskRows(due)}</section>`}
function tasksView(){return head('All tasks','Plan today, tomorrow or any future date','<button class="btn primary" onclick="taskModal()">+ New task</button>')+`<section class="card">${taskRows([...state.tasks].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')))}</section>`}
function analytics(){setTimeout(drawCharts);const completed=allTopics().filter(t=>t.status==='completed').length;return head('Progress analytics','Understand your momentum and consistency')+`<div class="grid stats"><div class="stat"><div><small>Study hours</small><strong>${Math.round(state.activity.reduce((a,x)=>a+x.minutes,0)/60)}</strong></div></div><div class="stat"><div><small>Topics completed</small><strong>${completed}</strong></div></div><div class="stat"><div><small>Accuracy</small><strong>${overall()}%</strong></div></div><div class="stat"><div><small>Current streak</small><strong>${streak()} days</strong></div></div></div><div class="grid analytics-grid"><section class="card"><div class="card-title"><h3>Subject progress</h3></div><div class="chart-box"><canvas id="progressChart"></canvas></div></section><section class="card"><div class="card-title"><h3>Status distribution</h3></div><div class="chart-box"><canvas id="statusChart"></canvas></div></section></div>`}
function drawCharts(){if(!window.Chart)return;Chart.defaults.color='#8493a9';new Chart(progressChart,{type:'bar',data:{labels:state.subjects.map(s=>s.name),datasets:[{data:state.subjects.map(pct),backgroundColor:state.subjects.map(s=>s.color),borderRadius:8}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,grid:{color:'#1d2c42'}},x:{grid:{display:false}}}}});const t=allTopics();new Chart(statusChart,{type:'doughnut',data:{labels:['Completed','In progress','Not started'],datasets:[{data:['completed','in-progress','not-started'].map(x=>t.filter(y=>y.status===x).length),backgroundColor:['#35d07f','#7c5cff','#29384d'],borderWidth:0}]},options:{maintainAspectRatio:false,cutout:'70%'}})}
function notes(){let n=state.notes.find(x=>x.id===selectedNote)||state.notes[0];return head('Notes','Keep methodology, commands and revision notes together','<button class="btn primary" onclick="newNote()">+ New note</button>')+`<div class="grid note-layout"><aside class="card note-list">${state.notes.map(x=>`<button class="note-item ${x.id===n?.id?'active':''}" onclick="selectNote('${x.id}')"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(subjectName(x.subjectId))} · ${x.updated}</small></button>`).join('')}</aside><section class="card note-editor">${n?`<input value="${escapeHtml(n.title)}" oninput="editNote('title',this.value)"><textarea oninput="editNote('content',this.value)">${escapeHtml(n.content)}</textarea><div class="modal-actions"><button class="btn danger" onclick="deleteNote('${n.id}')">Delete note</button></div>`:'<div class="empty">Create your first note.</div>'}</section></div>`}
function calendar(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),todayTasks=state.tasks.filter(t=>t.due===today());let cells='';for(let i=0;i<42;i++){let d,muted=false,month=m;if(i<start){d=prev-start+i+1;month=m-1;muted=true}else if(i>=start+days){d=i-start-days+1;month=m+1;muted=true}else d=i-start+1;const iso=new Date(y,month,d,12).toISOString().slice(0,10),items=[...state.tasks.filter(t=>t.due===iso).map(t=>({...t,kind:'task'})),...(state.events||[]).filter(e=>e.date===iso).map(e=>({...e,kind:'event'})),...allTopics().filter(t=>t.due===iso).map(t=>({id:t.id,title:t.name,kind:'topic'})),...(state.jobApplications||[]).filter(a=>a.followUpDate===iso&&!jobTerminal(a.status)).map(a=>({id:a.id,title:`Follow up: ${a.company}`,kind:'job'}))];cells+=`<button class="cal-day ${muted?'muted':''} ${iso===today()?'today':''}" onclick="calendarDay('${iso}')"><span class="cal-num">${d}</span>${items.slice(0,3).map(e=>`<span class="cal-event ${e.kind}">${escapeHtml(e.title)}</span>`).join('')}${items.length>3?`<small>+${items.length-3} more</small>`:''}</button>`}return head('Calendar & today plan','Study deadlines, today tasks, events and job follow-ups',`<div class="job-head-actions"><button class="btn ghost" onclick="taskModal()">+ Today task</button><button class="btn primary" onclick="eventModal()">+ Add event</button></div>`)+`<div class="grid calendar-layout"><section class="card calendar-card"><div class="calendar-head"><button class="icon-btn" onclick="moveMonth(-1)">‹</button><button class="btn ghost" onclick="calDate=new Date();render()">Today</button><h3>${calDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button class="icon-btn" onclick="moveMonth(1)">›</button></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="day-name">${x}</div>`).join('')}${cells}</div></section><aside class="card today-panel"><div class="card-title"><h3>Today plan</h3><span>${todayTasks.length} task${todayTasks.length===1?'':'s'}</span></div>${taskRows(todayTasks)}</aside></div>`}
function settings(){const themes=[['dark','#7c5cff'],['cyber','#ff3e9d'],['matrix','#3cdb71'],['ocean','#1b9cff'],['light','#dce8f5']];return head('User & app settings','Your complete account and application control center')+`<div class="grid settings-grid"><section class="card"><div class="card-title"><h3>Profile & security</h3></div><div class="setting-row"><span>Signed in as</span><strong>${escapeHtml(state.profile?.name||'Local user')}</strong></div><div class="setting-row"><span>Account email</span><strong>${escapeHtml(state.profile?.email||cloudUser?.email||'Local profile')}</strong></div><div class="modal-actions"><button class="btn primary" onclick="profileModal()">Edit profile / password</button></div></section><section class="card"><div class="card-title"><h3>Workspace control</h3><span>${state.workspaces.length} total</span></div><label class="workspace-switcher settings-workspace">Active workspace<select id="settingsWorkspaceSelect" aria-label="Current workspace" onchange="switchWorkspace(this.value)">${state.workspaces.filter(w=>!w.archived||w.id===state.activeWorkspace).map(w=>`<option value="${w.id}" ${w.id===state.activeWorkspace?'selected':''}>${escapeHtml(w.name)}</option>`).join('')}</select></label>${state.workspaces.map(w=>`<div class="setting-row"><span>${escapeHtml(w.name)} ${w.archived?'(Archived)':''}</span><button class="mini-btn" onclick="workspaceModal('${w.id}')">✎</button></div>`).join('')}<div class="modal-actions"><button class="btn primary" onclick="workspaceModal()">+ New workspace</button></div></section><section class="card"><div class="card-title"><h3>Appearance</h3></div><div class="theme-list">${themes.map(([n,c])=>`<button title="${n}" class="theme-chip ${state.settings.theme===n?'active':''}" style="--swatch:${c}" onclick="setTheme('${n}')"></button>`).join('')}</div></section><section class="card"><div class="card-title"><h3>Sound & notifications</h3></div><div class="setting-row"><span>Completion sound</span><button class="toggle ${state.settings.sounds?'on':''}" onclick="toggleSetting('sounds')"></button></div><div class="setting-row"><span>Deadline notifications</span><button class="toggle ${state.settings.notifications?'on':''}" onclick="toggleSetting('notifications')"></button></div></section><section class="card"><div class="card-title"><h3>Import / Export</h3></div><p class="task-meta">JSON preserves study and job data; Excel creates readable sheets.</p><div class="modal-actions"><button class="btn ghost" onclick="importInput.click()">Import JSON</button><button class="btn ghost" onclick="exportJSON()">Export JSON</button><button class="btn primary" onclick="exportExcel()">Export Excel</button></div></section></div>`}
function timerView(){const mins=String(Math.floor(timerSeconds/60)).padStart(2,'0'),secs=String(timerSeconds%60).padStart(2,'0');return head('Study timer','Complete focused sessions and automatically record study time')+`<section class="card timer-shell"><span class="eyebrow">FOCUS SESSION</span><div id="timerDisplay" class="timer-display">${mins}:${secs}</div><div class="timer-presets"><button class="btn ghost" onclick="setTimer(25)">25 min</button><button class="btn ghost" onclick="setTimer(45)">45 min</button><button class="btn ghost" onclick="setTimer(60)">60 min</button></div><p id="timerStatus" class="timer-status">${timerHandle?'Session running':'Ready when you are'}</p><div class="timer-actions"><button class="btn primary" onclick="startTimer()">▶ Start</button><button class="btn ghost" onclick="pauseTimer()">Pause</button><button class="btn danger" onclick="resetTimer()">Reset</button></div></section>`}
function render(){sideStreak.textContent=`${streak()} days`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===viewName));const views={dashboard,subjects,tasks:tasksView,notes,calendar,jobs:jobTracker,timer:timerView,settings,subject:subjectView};view.innerHTML=(views[viewName]||dashboard)()}
window.setView=n=>{viewName=n;document.querySelector('.sidebar').classList.remove('open');render()};window.openSubject=id=>{selectedSubject=id;viewName='subject';render()};
function modal(html){modalBody.innerHTML=html;const d=document.querySelector('#modal');if(!d.open)d.showModal()}function closeModal(){document.querySelector('#modal').close()}function field(id){return document.getElementById(id)}
window.subjectModal=id=>{const s=state.subjects.find(x=>x.id===id);modal(`<h2>${s?'Edit':'Add'} subject</h2><div class="form-grid"><label>Name<input id="fName" value="${escapeHtml(s?.name||'')}"></label><label>Short icon<input id="fIcon" maxlength="3" value="${escapeHtml(s?.icon||'')}"></label><label class="full">Description<input id="fDesc" value="${escapeHtml(s?.description||'')}"></label><label>Color<input id="fColor" type="color" value="${s?.color||'#7c5cff'}"></label></div><div class="modal-actions">${s?'<button type="button" class="btn danger" onclick="deleteSubject(\''+s.id+'\')">Delete</button>':''}<button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveSubject('${id||''}')">Save</button></div>`)};
window.saveSubject=id=>{const s=state.subjects.find(x=>x.id===id),name=field('fName').value.trim(),data={name,icon:(field('fIcon').value||name.slice(0,2)).toUpperCase(),description:field('fDesc').value.trim(),color:field('fColor').value};if(!data.name)return toast('Subject name is required');if(s)Object.assign(s,data);else state.subjects.push({id:uid(),...data,modules:[]});save();closeModal();render();toast('Subject saved')};
window.deleteSubject=id=>{if(!confirm('Delete this subject and all its modules?'))return;state.subjects=state.subjects.filter(s=>s.id!==id);save();closeModal();viewName='subjects';render()};
window.moduleModal=sid=>modal(`<h2>Add module</h2><label>Module name<input id="fModule"></label><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveModule('${sid}')">Add module</button></div>`);
window.saveModule=sid=>{const s=state.subjects.find(x=>x.id===sid),name=field('fModule').value.trim();if(!name)return toast('Module name is required');s.modules.push({id:uid(),name,topics:[]});save();closeModal();render();toast('Module added')};
window.topicModal=(sid,mid)=>modal(`<h2>Add topic</h2><div class="form-grid"><label class="full">Topic name<input id="fTopic"></label><label>Due date<input id="fDue" type="date"></label><label>Status<select id="fStatus"><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="completed">Completed</option></select></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveTopic('${sid}','${mid}')">Add topic</button></div>`);
function getTopic(sid,mid,tid){return state.subjects.find(s=>s.id===sid)?.modules.find(m=>m.id===mid)?.topics.find(t=>t.id===tid)}
window.saveTopic=(sid,mid)=>{const m=state.subjects.find(s=>s.id===sid).modules.find(x=>x.id===mid),name=field('fTopic').value.trim();if(!name)return toast('Topic name is required');m.topics.push({id:uid(),name,due:field('fDue').value,status:field('fStatus').value});save();closeModal();render();toast('Topic added')};
window.topicStatus=(s,m,t,v)=>{getTopic(s,m,t).status=v;save();render()};window.topicDue=(s,m,t,v)=>{getTopic(s,m,t).due=v;save()};window.cycleTopic=(s,m,t)=>{const x=getTopic(s,m,t);x.status=x.status==='completed'?'not-started':'completed';save();if(x.status==='completed')beep();render()};window.deleteTopic=(s,m,t)=>{const x=state.subjects.find(x=>x.id===s).modules.find(x=>x.id===m);x.topics=x.topics.filter(x=>x.id!==t);save();render()};
window.taskModal=id=>{const t=state.tasks.find(x=>x.id===id);modal(`<h2>${t?'Edit':'New'} study task</h2><div class="form-grid"><label class="full">Task title<input id="fTask" value="${escapeHtml(t?.title||'')}"></label><label>Subject<select id="fSubject">${state.subjects.map(s=>`<option value="${s.id}" ${t?.subjectId===s.id?'selected':''}>${escapeHtml(s.name)}</option>`).join('')}</select></label><label>Priority<select id="fPriority">${['low','medium','high'].map(p=>`<option ${t?.priority===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Due date<input id="fTaskDue" type="date" value="${t?.due||today()}"></label><label>Time<input id="fTime" type="time" value="${t?.time||''}"></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveTask('${id||''}')">${t?'Save changes':'Create task'}</button></div>`)};
window.saveTask=id=>{const title=field('fTask').value.trim();if(!title)return toast('Task title is required');const t=state.tasks.find(x=>x.id===id),data={title,subjectId:field('fSubject').value,priority:field('fPriority').value,due:field('fTaskDue').value,time:field('fTime').value};if(t)Object.assign(t,data);else state.tasks.push({id:uid(),...data,status:'pending'});save();closeModal();render();toast(t?'Task updated':'Task created')};window.deleteTask=id=>{if(!confirm('Delete this task?'))return;state.tasks=state.tasks.filter(t=>t.id!==id);save();render();toast('Task deleted')};window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);t.status=t.status==='completed'?'pending':'completed';if(t.status==='completed'){state.activity.push({date:today(),minutes:30});beep()}save();render()};
window.newNote=()=>{const n={id:uid(),title:'Untitled note',subjectId:state.subjects[0]?.id||'',content:'',updated:today()};state.notes.unshift(n);selectedNote=n.id;save();render()};window.selectNote=id=>{selectedNote=id;render()};window.editNote=(k,v)=>{const n=state.notes.find(x=>x.id===selectedNote);n[k]=v;n.updated=today();save()};window.deleteNote=id=>{state.notes=state.notes.filter(x=>x.id!==id);selectedNote=state.notes[0]?.id;save();render()};
window.moveMonth=n=>{calDate.setMonth(calDate.getMonth()+n);render()};window.setTheme=t=>{state.settings.theme=t;save();render()};window.toggleSetting=k=>{state.settings[k]=!state.settings[k];save();render()};
window.calendarDay=date=>{const existing=(state.events||[]).filter(e=>e.date===date),jobs=(state.jobApplications||[]).filter(a=>a.followUpDate===date&&!jobTerminal(a.status));modal(`<h2>${date}</h2>${existing.map(e=>`<div class="setting-row"><span><strong>${escapeHtml(e.title)}</strong><small>${e.time||'All day'}</small></span><span><button type="button" class="mini-btn" onclick="eventModal('${e.id}')">✎</button><button type="button" class="mini-btn" onclick="deleteEvent('${e.id}')">×</button></span></div>`).join('')}${jobs.map(a=>`<div class="setting-row"><span><strong>Job follow-up: ${escapeHtml(a.company)}</strong><small>${escapeHtml(a.jobTitle)}</small></span><button type="button" class="mini-btn" onclick="jobDetails('${a.id}')">→</button></div>`).join('')}${!existing.length&&!jobs.length?'<div class="empty">Nothing scheduled.</div>':''}<div class="modal-actions"><button class="btn ghost">Close</button><button type="button" class="btn primary" onclick="eventModal('', '${date}')">+ Add event</button></div>`)};
window.eventModal=(id='',date=today())=>{const e=(state.events||[]).find(x=>x.id===id);modal(`<h2>${e?'Edit':'Add'} calendar event</h2><div class="form-grid"><label class="full">Title<input id="fEventTitle" value="${escapeHtml(e?.title||'')}"></label><label>Date<input id="fEventDate" type="date" value="${e?.date||date}"></label><label>Time<input id="fEventTime" type="time" value="${e?.time||''}"></label><label>Repeat<select id="fEventRepeat"><option value="none">Does not repeat</option><option value="weekly" ${e?.repeat==='weekly'?'selected':''}>Weekly</option><option value="monthly" ${e?.repeat==='monthly'?'selected':''}>Monthly</option></select></label><label>Color<input id="fEventColor" type="color" value="${e?.color||'#7c5cff'}"></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveEvent('${id}')">Save event</button></div>`)};
window.saveEvent=id=>{const title=field('fEventTitle').value.trim();if(!title)return toast('Event title is required');state.events=state.events||[];const data={title,date:field('fEventDate').value,time:field('fEventTime').value,repeat:field('fEventRepeat').value,color:field('fEventColor').value},e=state.events.find(x=>x.id===id);if(e)Object.assign(e,data);else state.events.push({id:uid(),...data});save();closeModal();render();toast('Event saved')};
window.deleteEvent=id=>{state.events=state.events.filter(e=>e.id!==id);save();closeModal();render();toast('Event deleted')};
function workspaceData(){return {subjects:structuredClone(state.subjects),tasks:structuredClone(state.tasks),events:structuredClone(state.events||[]),jobApplications:structuredClone(state.jobApplications||[]),notes:structuredClone(state.notes),activity:structuredClone(state.activity)}}
function storeWorkspace(){const w=state.workspaces.find(x=>x.id===state.activeWorkspace);if(w)w.data=workspaceData()}
window.switchWorkspace=id=>{if(id===state.activeWorkspace)return;storeWorkspace();const w=state.workspaces.find(x=>x.id===id);if(!w)return;state.activeWorkspace=id;const d=w.data||{subjects:[],tasks:[],events:[],jobApplications:[],notes:[],activity:[]};Object.assign(state,structuredClone(d));state.jobApplications=state.jobApplications||[];selectedSubject=state.subjects[0]?.id||'';selectedNote=state.notes[0]?.id;save();viewName='dashboard';render();toast(`Workspace: ${w.name}`)};
window.workspaceModal=id=>{const w=state.workspaces.find(x=>x.id===id);modal(`<h2>${w?'Edit':'Create'} workspace</h2><label>Workspace name<input id="fWorkspace" value="${escapeHtml(w?.name||'')}"></label><div class="modal-actions">${w&&state.workspaces.length>1?`<button type="button" class="btn danger" onclick="deleteWorkspace('${id}')">Delete</button>`:''}${w?`<button type="button" class="btn ghost" onclick="archiveWorkspace('${id}')">${w.archived?'Restore':'Archive'}</button>`:''}<button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveWorkspace('${id||''}')">Save</button></div>`)};
window.saveWorkspace=id=>{const name=field('fWorkspace').value.trim();if(!name)return toast('Workspace name is required');if(id){state.workspaces.find(x=>x.id===id).name=name}else{storeWorkspace();const w={id:uid(),name,archived:false,data:{subjects:[],tasks:[],events:[],jobApplications:[],notes:[],activity:[]}};state.workspaces.push(w);state.activeWorkspace=w.id;Object.assign(state,structuredClone(w.data))}save();closeModal();viewName='dashboard';render()};
window.archiveWorkspace=id=>{const w=state.workspaces.find(x=>x.id===id);w.archived=!w.archived;save();closeModal();render()};
window.deleteWorkspace=id=>{if(!confirm('Delete this workspace and its data?'))return;state.workspaces=state.workspaces.filter(w=>w.id!==id);const next=state.workspaces[0];state.activeWorkspace=next.id;Object.assign(state,structuredClone(next.data||{subjects:[],tasks:[],events:[],jobApplications:[],notes:[],activity:[]}));save();closeModal();render()};
window.profileModal=()=>modal(`<h2>User profile</h2><div class="form-grid"><label class="full">Display name<input id="fProfileName" value="${escapeHtml(state.profile?.name||'')}"></label><label class="full">New local PIN / password<input id="fProfilePin" type="password" minlength="4" placeholder="Leave blank to keep current"></label></div><p class="task-meta">When Supabase is connected, password reset and account security are handled by secure email verification.</p><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveProfile()">Save profile</button></div>`);
window.saveProfile=async()=>{state.profile.name=field('fProfileName').value.trim()||state.profile.name;const p=field('fProfilePin').value;if(p&&cloudUser&&sb){const {error}=await sb.auth.updateUser({password:p,data:{full_name:state.profile.name}});if(error)return toast(error.message)}else if(p)state.profile.pin=p;save();avatar.textContent=state.profile.name[0].toUpperCase();closeModal();render();toast('Profile updated')};
function paintTimer(){const el=document.getElementById('timerDisplay');if(el)el.textContent=`${String(Math.floor(timerSeconds/60)).padStart(2,'0')}:${String(timerSeconds%60).padStart(2,'0')}`}window.setTimer=m=>{window.pauseTimer();timerInitial=m*60;timerSeconds=timerInitial;paintTimer();toast(`${m}-minute timer ready`)};window.startTimer=()=>{if(timerHandle)return;timerHandle=setInterval(()=>{timerSeconds--;paintTimer();if(timerSeconds<=0){clearInterval(timerHandle);timerHandle=null;state.activity.push({date:today(),minutes:Math.round(timerInitial/60)});save();beep();timerSeconds=timerInitial;render();toast('Focus session completed!')}},1000);render()};window.pauseTimer=()=>{if(timerHandle){clearInterval(timerHandle);timerHandle=null}paintTimer()};window.resetTimer=()=>{window.pauseTimer();timerSeconds=timerInitial;render()};
window.exportJSON=()=>download(`study-tracker-${today()}.json`,JSON.stringify(state,null,2),'application/json');function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
window.exportExcel=()=>{if(!window.XLSX)return toast('Excel library unavailable');const wb=XLSX.utils.book_new(),rows=allTopics().map(t=>({Subject:subjectName(t.subjectId),Module:t.module,Topic:t.name,Status:t.status,'Due Date':t.due||''}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Progress');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.tasks.map(t=>({...t,subject:subjectName(t.subjectId)}))),'Tasks');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet((state.jobApplications||[]).map(a=>({Company:a.company,'Job Title':a.jobTitle,'Job ID':a.jobId,Platform:a.platform,Location:a.location,Status:a.status,'Applied Date':a.appliedDate,'Follow-up Date':a.followUpDate,'Salary / CTC':a.salary,Contact:a.contactName,Email:a.contactEmail,'Job URL':a.jobUrl,Notes:a.notes,Resume:a.resume?.name||'','Cover Letter':a.coverLetter?.name||''}))),'Job Applications');XLSX.writeFile(wb,`study-tracker-${today()}.xlsx`)};
importInput.addEventListener('change',e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.subjects||!x.tasks)throw Error();state=normalizeState(x);save();render();toast('Backup imported')}catch{toast('Invalid tracker backup')}};r.readAsText(e.target.files[0])});
nav.addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)setView(b.dataset.view)});menuBtn.onclick=()=>document.querySelector('.sidebar').classList.toggle('open');quickAdd.onclick=()=>taskModal();logoutBtn.onclick=async()=>{if(sb&&cloudUser)await sb.auth.signOut();cloudUser=null;state.profile=null;localStorage.removeItem(KEY);location.reload()};loginForm.addEventListener('submit',login);googleLoginBtn.onclick=()=>{if(!sb)return toast('Cloud login is unavailable');sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}})};avatar.onclick=()=>setView('settings');analogClock.onclick=()=>setView('calendar');sideTimer.onclick=()=>setView('timer');globalSearch.addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(q.length<2)return;const s=state.subjects.find(x=>x.name.toLowerCase().includes(q));if(s){selectedSubject=s.id;viewName='subject';return render()}const j=(state.jobApplications||[]).find(x=>`${x.company} ${x.jobTitle}`.toLowerCase().includes(q));if(j){jobQuery=q;viewName='jobs';render()}});notifBtn.onclick=()=>{const overdue=state.tasks.filter(t=>t.due<today()&&t.status!=='completed').length,jobs=(state.jobApplications||[]).filter(jobDue).length;toast(overdue||jobs?`${overdue} overdue study task${overdue===1?'':'s'} · ${jobs} job follow-up${jobs===1?'':'s'} due`:'You are all caught up')};
function tickClock(){const d=new Date(),h=(d.getHours()%12)*30+d.getMinutes()/2,m=d.getMinutes()*6,s=d.getSeconds()*6;analogClock.querySelector('.hour').style.transform=`rotate(${h}deg)`;analogClock.querySelector('.minute').style.transform=`rotate(${m}deg)`;analogClock.querySelector('.second').style.transform=`rotate(${s}deg)`}tickClock();setInterval(tickClock,1000);
async function boot(){applyTheme();if(sb){const {data}=await sb.auth.getSession();if(data.session){cloudUser=data.session.user;try{await loadCloud();showApp()}catch(e){toast('Cloud data could not be loaded')}}else if(state.profile)showApp()}else if(state.profile)showApp()}boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
