const KEY='studyTracker.v21';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2,10);
const seed={profile:null,settings:{theme:'dark',sounds:true,notifications:true},subjects:[
 {id:'oscp',name:'OSCP',description:'Offensive Security Certified Professional',color:'#7c5cff',icon:'OS',modules:[
  {id:uid(),name:'Information Gathering',topics:[{id:uid(),name:'Passive Reconnaissance',status:'completed',due:today()},{id:uid(),name:'Active Scanning',status:'completed',due:today()}]},
  {id:uid(),name:'Enumeration',topics:[{id:uid(),name:'Nmap Service Enumeration',status:'in-progress',due:today()},{id:uid(),name:'SMB & SNMP Enumeration',status:'not-started',due:''}]},
  {id:uid(),name:'Web Exploitation',topics:[{id:uid(),name:'SQL Injection',status:'completed',due:''},{id:uid(),name:'XSS Attacks',status:'in-progress',due:''},{id:uid(),name:'File Inclusion',status:'not-started',due:''}]},
  {id:uid(),name:'Privilege Escalation',topics:[{id:uid(),name:'Linux Privilege Escalation',status:'not-started',due:''},{id:uid(),name:'Windows Privilege Escalation',status:'not-started',due:''}]},
  {id:uid(),name:'Active Directory',topics:[{id:uid(),name:'AD Enumeration',status:'not-started',due:''},{id:uid(),name:'Kerberos Attacks',status:'not-started',due:''}]}]},
 {id:'python',name:'Python',description:'Automation and security scripting',color:'#20c997',icon:'PY',modules:[{id:uid(),name:'Python Core',topics:[{id:uid(),name:'Requests & HTTP',status:'in-progress',due:''},{id:uid(),name:'File Parsing',status:'not-started',due:''}]}]},
 {id:'network',name:'Networking',description:'Network fundamentals and analysis',color:'#ff9f43',icon:'NW',modules:[{id:uid(),name:'TCP/IP',topics:[{id:uid(),name:'Packet Analysis',status:'not-started',due:''}]}]}
],tasks:[{id:uid(),title:'Nmap service-enumeration practice',subjectId:'oscp',due:today(),time:'19:00',status:'pending',priority:'high'},{id:uid(),title:'Revise Python requests',subjectId:'python',due:today(),time:'21:00',status:'pending',priority:'medium'}],notes:[{id:uid(),title:'OSCP Methodology',subjectId:'oscp',content:'Enumeration first. Build a service map, validate every assumption, and keep structured notes.',updated:today()}],activity:[{date:today(),minutes:90}]};
let state=load(),viewName='dashboard',selectedSubject='oscp',selectedNote=state.notes[0]?.id,calDate=new Date();
function load(){try{return Object.assign(structuredClone(seed),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));applyTheme()}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pct(subject){const t=subject.modules.flatMap(m=>m.topics);return t.length?Math.round(t.filter(x=>x.status==='completed').length/t.length*100):0}
function allTopics(){return state.subjects.flatMap(s=>s.modules.flatMap(m=>m.topics.map(t=>({...t,subjectId:s.id,subject:s.name,module:m.name}))))}
function overall(){const t=allTopics();return t.length?Math.round(t.filter(x=>x.status==='completed').length/t.length*100):0}
function streak(){const days=new Set(state.activity.filter(a=>a.minutes>0).map(a=>a.date));let n=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function subjectName(id){return state.subjects.find(s=>s.id===id)?.name||'General'}
function toast(msg){const x=document.querySelector('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function applyTheme(){document.body.className=state.settings.theme==='dark'?'':`theme-${state.settings.theme}`}
function beep(){if(!state.settings.sounds)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=520;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}
function login(e){e.preventDefault();const name=loginName.value.trim(),pin=loginPin.value;if(state.profile&&state.profile.pin!==pin)return toast('Incorrect PIN');state.profile={name,pin};save();showApp()}
function showApp(){authScreen.classList.add('hidden');app.classList.remove('hidden');avatar.textContent=(state.profile?.name||'P')[0].toUpperCase();render()}
function head(title,sub,action=''){return `<div class="page-head"><div><span class="eyebrow">STUDY TRACKER</span><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function taskRows(tasks){if(!tasks.length)return '<div class="empty">No tasks here yet.</div>';return `<div class="task-list">${tasks.map(t=>{const overdue=t.due&&t.due<today()&&t.status!=='completed';return `<div class="task-row ${t.status==='completed'?'done':''}"><button class="check ${t.status==='completed'?'checked':''}" onclick="toggleTask('${t.id}')">${t.status==='completed'?'✓':''}</button><div><div class="task-name">${escapeHtml(t.title)}</div><div class="task-meta">${escapeHtml(subjectName(t.subjectId))} · ${t.due||'No date'} ${t.time||''}</div></div><span class="badge ${overdue?'danger':t.priority==='high'?'warn':''}">${overdue?'Overdue':t.priority}</span></div>`}).join('')}</div>`}
function dashboard(){const p=overall(),due=state.tasks.filter(t=>t.status!=='completed'&&t.due===today()),completed=allTopics().filter(t=>t.status==='completed').length;return head(`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${escapeHtml(state.profile.name.split(' ')[0])}`,"Let's continue your learning journey")+`<div class="grid stats"><div class="stat"><div class="stat-icon">◫</div><div><small>Total subjects</small><strong>${state.subjects.length}</strong></div></div><div class="stat"><div class="stat-icon">✓</div><div><small>Topics completed</small><strong>${completed}</strong></div></div><div class="stat"><div class="stat-icon">◷</div><div><small>Due today</small><strong>${due.length}</strong></div></div><div class="stat"><div class="stat-icon">⌁</div><div><small>Study hours</small><strong>${Math.round(state.activity.reduce((a,x)=>a+x.minutes,0)/60)}h</strong></div></div></div><div class="grid dashboard-grid"><section class="card"><div class="card-title"><h3>Overall progress</h3><span>All subjects</span></div><div class="overview-flex"><div class="progress-ring" style="--p:${p}"><div><strong>${p}%</strong><small>completed</small></div></div><div class="subject-bars">${state.subjects.slice(0,5).map(s=>`<div class="bar-row"><span>${escapeHtml(s.name)}</span><div class="bar"><i style="width:${pct(s)}%"></i></div><b>${pct(s)}%</b></div>`).join('')}</div></div></section><section class="card"><div class="card-title"><h3>Today plan</h3><button class="kebab" onclick="setView('today')">→</button></div>${taskRows(due)}</section><section class="card span-2"><div class="card-title"><h3>Upcoming deadlines</h3><span>Next tasks</span></div>${taskRows(state.tasks.filter(t=>t.status!=='completed').sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,5))}</section></div>`}
function subjects(){return head('My subjects','Manage all your learning tracks','<button class="btn primary" onclick="subjectModal()">+ Add subject</button>')+`<div class="grid subject-grid">${state.subjects.map(s=>`<article class="card subject-card" style="--subject:${s.color}" onclick="openSubject('${s.id}')"><div class="subject-top"><div class="subject-icon">${escapeHtml(s.icon)}</div><button class="kebab" onclick="event.stopPropagation();subjectModal('${s.id}')">•••</button></div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p><div class="progress-line"><i style="width:${pct(s)}%"></i></div><div class="progress-label"><span>${s.modules.length} modules</span><strong>${pct(s)}%</strong></div></article>`).join('')}</div>`}
function subjectView(){const s=state.subjects.find(x=>x.id===selectedSubject)||state.subjects[0];if(!s)return subjects();return head(`${escapeHtml(s.name)} tracker`,escapeHtml(s.description),`<button class="btn primary" onclick="moduleModal('${s.id}')">+ Add module</button>`)+`<div class="grid stats"><div class="stat"><div><small>Overall progress</small><strong>${pct(s)}%</strong></div></div><div class="stat"><div><small>Modules</small><strong>${s.modules.length}</strong></div></div><div class="stat"><div><small>Topics</small><strong>${s.modules.flatMap(m=>m.topics).length}</strong></div></div><div class="stat"><div><small>Completed</small><strong>${s.modules.flatMap(m=>m.topics).filter(t=>t.status==='completed').length}</strong></div></div></div><div class="grid">${s.modules.map((m,i)=>`<section class="card module"><div class="module-head"><h3>${i+1}. ${escapeHtml(m.name)}</h3><button class="btn ghost" onclick="topicModal('${s.id}','${m.id}')">+ Topic</button></div><div class="module-body">${m.topics.length?m.topics.map(t=>`<div class="subtopic-row"><button class="check ${t.status==='completed'?'checked':''}" onclick="cycleTopic('${s.id}','${m.id}','${t.id}')">${t.status==='completed'?'✓':''}</button><span>${escapeHtml(t.name)}</span><select onchange="topicStatus('${s.id}','${m.id}','${t.id}',this.value)"><option value="not-started" ${t.status==='not-started'?'selected':''}>Not started</option><option value="in-progress" ${t.status==='in-progress'?'selected':''}>In progress</option><option value="completed" ${t.status==='completed'?'selected':''}>Completed</option></select><input type="date" value="${t.due||''}" onchange="topicDue('${s.id}','${m.id}','${t.id}',this.value)"><button class="kebab" onclick="deleteTopic('${s.id}','${m.id}','${t.id}')">×</button></div>`).join(''):'<div class="empty">No topics in this module.</div>'}</div></section>`).join('')}</div>`}
function todayView(){const due=state.tasks.filter(t=>t.due===today());return head('Today plan',new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}),'<button class="btn primary" onclick="taskModal()">+ New task</button>')+`<section class="card">${taskRows(due)}</section>`}
function tasksView(){return head('All tasks','Plan today, tomorrow or any future date','<button class="btn primary" onclick="taskModal()">+ New task</button>')+`<section class="card">${taskRows([...state.tasks].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')))}</section>`}
function analytics(){setTimeout(drawCharts);const completed=allTopics().filter(t=>t.status==='completed').length;return head('Progress analytics','Understand your momentum and consistency')+`<div class="grid stats"><div class="stat"><div><small>Study hours</small><strong>${Math.round(state.activity.reduce((a,x)=>a+x.minutes,0)/60)}</strong></div></div><div class="stat"><div><small>Topics completed</small><strong>${completed}</strong></div></div><div class="stat"><div><small>Accuracy</small><strong>${overall()}%</strong></div></div><div class="stat"><div><small>Current streak</small><strong>${streak()} days</strong></div></div></div><div class="grid analytics-grid"><section class="card"><div class="card-title"><h3>Subject progress</h3></div><div class="chart-box"><canvas id="progressChart"></canvas></div></section><section class="card"><div class="card-title"><h3>Status distribution</h3></div><div class="chart-box"><canvas id="statusChart"></canvas></div></section></div>`}
function drawCharts(){if(!window.Chart)return;Chart.defaults.color='#8493a9';new Chart(progressChart,{type:'bar',data:{labels:state.subjects.map(s=>s.name),datasets:[{data:state.subjects.map(pct),backgroundColor:state.subjects.map(s=>s.color),borderRadius:8}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,grid:{color:'#1d2c42'}},x:{grid:{display:false}}}}});const t=allTopics();new Chart(statusChart,{type:'doughnut',data:{labels:['Completed','In progress','Not started'],datasets:[{data:['completed','in-progress','not-started'].map(x=>t.filter(y=>y.status===x).length),backgroundColor:['#35d07f','#7c5cff','#29384d'],borderWidth:0}]},options:{maintainAspectRatio:false,cutout:'70%'}})}
function notes(){let n=state.notes.find(x=>x.id===selectedNote)||state.notes[0];return head('Notes','Keep methodology, commands and revision notes together','<button class="btn primary" onclick="newNote()">+ New note</button>')+`<div class="grid note-layout"><aside class="card note-list">${state.notes.map(x=>`<button class="note-item ${x.id===n?.id?'active':''}" onclick="selectNote('${x.id}')"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(subjectName(x.subjectId))} · ${x.updated}</small></button>`).join('')}</aside><section class="card note-editor">${n?`<input value="${escapeHtml(n.title)}" oninput="editNote('title',this.value)"><textarea oninput="editNote('content',this.value)">${escapeHtml(n.content)}</textarea><div class="modal-actions"><button class="btn danger" onclick="deleteNote('${n.id}')">Delete note</button></div>`:'<div class="empty">Create your first note.</div>'}</section></div>`}
function calendar(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();let cells='';for(let i=0;i<42;i++){let d,muted=false,month=m;if(i<start){d=prev-start+i+1;month=m-1;muted=true}else if(i>=start+days){d=i-start-days+1;month=m+1;muted=true}else d=i-start+1;const iso=new Date(y,month,d,12).toISOString().slice(0,10),events=state.tasks.filter(t=>t.due===iso);cells+=`<div class="cal-day ${muted?'muted':''} ${iso===today()?'today':''}"><span class="cal-num">${d}</span>${events.slice(0,3).map(e=>`<span class="cal-event">${escapeHtml(e.title)}</span>`).join('')}</div>`}return head('Calendar','See your study schedule and deadlines')+`<section class="card"><div class="calendar-head"><button class="icon-btn" onclick="moveMonth(-1)">‹</button><h3>${calDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button class="icon-btn" onclick="moveMonth(1)">›</button></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="day-name">${x}</div>`).join('')}${cells}</div></section>`}
function settings(){const themes=[['dark','#7c5cff'],['cyber','#ff3e9d'],['matrix','#3cdb71'],['ocean','#1b9cff'],['light','#dce8f5']];return head('Settings','Personalize, back up and move your study data')+`<div class="grid settings-grid"><section class="card"><div class="card-title"><h3>Appearance</h3></div><div class="theme-list">${themes.map(([n,c])=>`<button title="${n}" class="theme-chip ${state.settings.theme===n?'active':''}" style="--swatch:${c}" onclick="setTheme('${n}')"></button>`).join('')}</div></section><section class="card"><div class="card-title"><h3>Sound & notifications</h3></div><div class="setting-row"><span>Completion sound</span><button class="toggle ${state.settings.sounds?'on':''}" onclick="toggleSetting('sounds')"></button></div><div class="setting-row"><span>Deadline notifications</span><button class="toggle ${state.settings.notifications?'on':''}" onclick="toggleSetting('notifications')"></button></div></section><section class="card"><div class="card-title"><h3>Import / Export</h3></div><p class="task-meta">JSON preserves the complete tracker. Excel creates a readable progress workbook.</p><div class="modal-actions"><button class="btn ghost" onclick="importInput.click()">Import JSON</button><button class="btn ghost" onclick="exportJSON()">Export JSON</button><button class="btn primary" onclick="exportExcel()">Export Excel</button></div></section><section class="card"><div class="card-title"><h3>Profile</h3></div><div class="setting-row"><span>Local profile</span><strong>${escapeHtml(state.profile.name)}</strong></div><div class="setting-row"><span>Storage</span><span class="badge success">Saved locally</span></div></section></div>`}
function render(){sideStreak.textContent=`${streak()} day streak`;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===viewName));const views={dashboard,subjects,today:todayView,tasks:tasksView,analytics,notes,calendar,settings,subject:subjectView};view.innerHTML=(views[viewName]||dashboard)()}
window.setView=n=>{viewName=n;document.querySelector('.sidebar').classList.remove('open');render()};window.openSubject=id=>{selectedSubject=id;viewName='subject';render()};
function modal(html){modalBody.innerHTML=html;document.querySelector('#modal').showModal()}
window.subjectModal=id=>{const s=state.subjects.find(x=>x.id===id);modal(`<h2>${s?'Edit':'Add'} subject</h2><div class="form-grid"><label>Name<input id="fName" value="${escapeHtml(s?.name||'')}"></label><label>Short icon<input id="fIcon" maxlength="3" value="${escapeHtml(s?.icon||'')}"></label><label class="full">Description<input id="fDesc" value="${escapeHtml(s?.description||'')}"></label><label>Color<input id="fColor" type="color" value="${s?.color||'#7c5cff'}"></label></div><div class="modal-actions">${s?'<button type="button" class="btn danger" onclick="deleteSubject(\''+s.id+'\')">Delete</button>':''}<button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveSubject('${id||''}')">Save</button></div>`)};
window.saveSubject=id=>{const s=state.subjects.find(x=>x.id===id),data={name:fName.value.trim(),icon:(fIcon.value||fName.value.slice(0,2)).toUpperCase(),description:fDesc.value.trim(),color:fColor.value};if(!data.name)return toast('Subject name is required');if(s)Object.assign(s,data);else state.subjects.push({id:uid(),...data,modules:[]});save();modal.close();render();toast('Subject saved')};
window.deleteSubject=id=>{if(!confirm('Delete this subject and all its modules?'))return;state.subjects=state.subjects.filter(s=>s.id!==id);save();modal.close();viewName='subjects';render()};
window.moduleModal=sid=>modal(`<h2>Add module</h2><label>Module name<input id="fModule"></label><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveModule('${sid}')">Add module</button></div>`);
window.saveModule=sid=>{const s=state.subjects.find(x=>x.id===sid);if(!fModule.value.trim())return;s.modules.push({id:uid(),name:fModule.value.trim(),topics:[]});save();modal.close();render()};
window.topicModal=(sid,mid)=>modal(`<h2>Add topic</h2><div class="form-grid"><label class="full">Topic name<input id="fTopic"></label><label>Due date<input id="fDue" type="date"></label><label>Status<select id="fStatus"><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="completed">Completed</option></select></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveTopic('${sid}','${mid}')">Add topic</button></div>`);
function getTopic(sid,mid,tid){return state.subjects.find(s=>s.id===sid)?.modules.find(m=>m.id===mid)?.topics.find(t=>t.id===tid)}
window.saveTopic=(sid,mid)=>{const m=state.subjects.find(s=>s.id===sid).modules.find(x=>x.id===mid);if(!fTopic.value.trim())return;m.topics.push({id:uid(),name:fTopic.value.trim(),due:fDue.value,status:fStatus.value});save();modal.close();render()};
window.topicStatus=(s,m,t,v)=>{getTopic(s,m,t).status=v;save();render()};window.topicDue=(s,m,t,v)=>{getTopic(s,m,t).due=v;save()};window.cycleTopic=(s,m,t)=>{const x=getTopic(s,m,t);x.status=x.status==='completed'?'not-started':'completed';save();if(x.status==='completed')beep();render()};window.deleteTopic=(s,m,t)=>{const x=state.subjects.find(x=>x.id===s).modules.find(x=>x.id===m);x.topics=x.topics.filter(x=>x.id!==t);save();render()};
window.taskModal=()=>modal(`<h2>New study task</h2><div class="form-grid"><label class="full">Task title<input id="fTask"></label><label>Subject<select id="fSubject">${state.subjects.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}</select></label><label>Priority<select id="fPriority"><option>medium</option><option>high</option><option>low</option></select></label><label>Due date<input id="fTaskDue" type="date" value="${today()}"></label><label>Time<input id="fTime" type="time"></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveTask()">Create task</button></div>`);
window.saveTask=()=>{if(!fTask.value.trim())return toast('Task title is required');state.tasks.push({id:uid(),title:fTask.value.trim(),subjectId:fSubject.value,priority:fPriority.value,due:fTaskDue.value,time:fTime.value,status:'pending'});save();modal.close();render();toast('Task created')};window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);t.status=t.status==='completed'?'pending':'completed';if(t.status==='completed'){state.activity.push({date:today(),minutes:30});beep()}save();render()};
window.newNote=()=>{const n={id:uid(),title:'Untitled note',subjectId:state.subjects[0]?.id||'',content:'',updated:today()};state.notes.unshift(n);selectedNote=n.id;save();render()};window.selectNote=id=>{selectedNote=id;render()};window.editNote=(k,v)=>{const n=state.notes.find(x=>x.id===selectedNote);n[k]=v;n.updated=today();save()};window.deleteNote=id=>{state.notes=state.notes.filter(x=>x.id!==id);selectedNote=state.notes[0]?.id;save();render()};
window.moveMonth=n=>{calDate.setMonth(calDate.getMonth()+n);render()};window.setTheme=t=>{state.settings.theme=t;save();render()};window.toggleSetting=k=>{state.settings[k]=!state.settings[k];save();render()};
window.exportJSON=()=>download(`study-tracker-${today()}.json`,JSON.stringify(state,null,2),'application/json');function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
window.exportExcel=()=>{if(!window.XLSX)return toast('Excel library unavailable');const wb=XLSX.utils.book_new(),rows=allTopics().map(t=>({Subject:subjectName(t.subjectId),Module:t.module,Topic:t.name,Status:t.status,'Due Date':t.due||''}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Progress');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.tasks.map(t=>({...t,subject:subjectName(t.subjectId)}))),'Tasks');XLSX.writeFile(wb,`study-tracker-${today()}.xlsx`)};
importInput.addEventListener('change',e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.subjects||!x.tasks)throw Error();state=x;save();render();toast('Backup imported')}catch{toast('Invalid tracker backup')}};r.readAsText(e.target.files[0])});
nav.addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)setView(b.dataset.view)});menuBtn.onclick=()=>document.querySelector('.sidebar').classList.toggle('open');quickAdd.onclick=taskModal;logoutBtn.onclick=()=>{state.profile=null;save();location.reload()};loginForm.addEventListener('submit',login);globalSearch.addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(q.length<2)return;const s=state.subjects.find(x=>x.name.toLowerCase().includes(q));if(s){selectedSubject=s.id;viewName='subject';render()}});notifBtn.onclick=()=>{const overdue=state.tasks.filter(t=>t.due<today()&&t.status!=='completed').length;toast(overdue?`${overdue} overdue task${overdue>1?'s':''}`:'You are all caught up')};
applyTheme();if(state.profile)showApp();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
