const FAMILY_KEY='studyTracker.family.v1',FAMILY_SESSION='studyTracker.family.role';
let familyData=loadFamily(),activityTimer=null,lastActivityAt=Date.now(),lastActivityTick=Date.now(),trackedView='dashboard',parentWorkspaceMode=false;
function loadFamily(){try{return Object.assign({admin:null,invites:[],links:[],activity:{},settings:{voice:'calm-female',voiceRate:1,voicePitch:1,autoBriefing:true}},JSON.parse(localStorage.getItem(FAMILY_KEY)||'{}'))}catch{return {admin:null,invites:[],links:[],activity:{},settings:{voice:'calm-female',voiceRate:1,voicePitch:1,autoBriefing:true}}}}
function saveFamily(){localStorage.setItem(FAMILY_KEY,JSON.stringify(familyData))}
function familyId(){if(!state?.profile)return'';if(!state.profile.familyUserId){state.profile.familyUserId=`user-${uid()}-${uid()}`;save()}return state.profile.familyUserId}
async function familyHash(value,salt){const data=new TextEncoder().encode(`${salt}:${value}`),hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function isParentSession(){return sessionStorage.getItem(FAMILY_SESSION)==='parent'}
function familyActivity(){const id=familyId();if(!id)return null;return familyData.activity[id]||(familyData.activity[id]={name:state.profile?.name||'Learner',days:{},sessions:[],lastSeen:new Date().toISOString()})}
function activityDay(){const a=familyActivity();if(!a)return null;const key=today();return a.days[key]||(a.days[key]={activeMs:0,idleMs:0,viewChanges:0,views:{},logins:0})}
function markActivity(){lastActivityAt=Date.now()}
function activityTick(){if(isParentSession()||!state?.profile)return;const now=Date.now(),delta=Math.min(15000,now-lastActivityTick);lastActivityTick=now;const day=activityDay();if(!day)return;const active=document.visibilityState==='visible'&&document.hasFocus()&&now-lastActivityAt<120000;if(active){day.activeMs+=delta;day.views[trackedView]=(day.views[trackedView]||0)+delta}else day.idleMs+=delta;const a=familyActivity();a.lastSeen=new Date().toISOString();saveFamily()}
function startActivityTracking(){if(activityTimer)return;const day=activityDay();if(day)day.logins++;const a=familyActivity();if(a){a.sessions.push({startedAt:new Date().toISOString()});a.sessions=a.sessions.slice(-100);saveFamily()}['mousemove','mousedown','keydown','touchstart','scroll'].forEach(e=>addEventListener(e,markActivity,{passive:true}));document.addEventListener('visibilitychange',activityTick);activityTimer=setInterval(activityTick,5000)}
function trackFamilyView(name){if(isParentSession())return;activityTick();if(name!==trackedView){const day=activityDay();if(day)day.viewChanges++;trackedView=name;saveFamily()}}
function formatDuration(ms=0){const mins=Math.round(ms/60000);return mins<60?`${mins}m`:`${Math.floor(mins/60)}h ${mins%60}m`}
function voiceProfiles(){return [['calm-female','Calm Female'],['clear-female','Clear Female'],['calm-male','Calm Male'],['deep-male','Deep Male'],['system','System Default']]}
function chooseVoice(profile){const voices=speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang)),female=voices.filter(v=>/female|zira|samantha|victoria|aria|jenny|google uk english female/i.test(v.name)),male=voices.filter(v=>/male|david|mark|daniel|george|guy|google uk english male/i.test(v.name));if(profile==='calm-female')return female[0]||voices[0];if(profile==='clear-female')return female[1]||female[0]||voices[1]||voices[0];if(profile==='calm-male')return male[0]||voices[0];if(profile==='deep-male')return male[1]||male[0]||voices[1]||voices[0];return voices[0]||speechSynthesis.getVoices()[0]}
window.familySpeak=(text)=>{if(!('speechSynthesis'in window))return toast('Voice is not supported on this browser');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||''));u.voice=chooseVoice(familyData.settings.voice);u.rate=Number(familyData.settings.voiceRate)||1;u.pitch=Number(familyData.settings.voicePitch)||1;speechSynthesis.speak(u)};
window.familySpeakBriefing=()=>{const el=document.querySelector('.briefing');if(el)familySpeak(el.innerText.replace(/Job Tracker\s+Open calendar\s+Start my day/g,''))};
window.familyStopVoice=()=>speechSynthesis?.cancel();
window.setFamilyVoice=(key,value)=>{familyData.settings[key]=key==='autoBriefing'?Boolean(value):value;saveFamily();if(key==='voice')familySpeak(`Hello. You selected ${voiceProfiles().find(x=>x[0]===value)?.[1]||'this voice'}.`)};
function familySettingsCards(){const id=familyId(),linked=familyData.links.some(l=>l.userId===id),voice=familyData.settings.voice;return `<section class="card"><div class="card-title"><h3>Voice & daily briefing</h3><span>5 profiles</span></div><label class="workspace-switcher">Briefing voice<select onchange="setFamilyVoice('voice',this.value)">${voiceProfiles().map(([v,n])=>`<option value="${v}" ${voice===v?'selected':''}>${n}</option>`).join('')}</select></label><div class="setting-row"><span>Read briefing automatically</span><button class="toggle ${familyData.settings.autoBriefing?'on':''}" onclick="setFamilyVoice('autoBriefing',!${familyData.settings.autoBriefing});render()"></button></div><label>Speaking speed<input type="range" min="0.7" max="1.3" step="0.1" value="${familyData.settings.voiceRate}" onchange="setFamilyVoice('voiceRate',this.value)"></label><div class="modal-actions"><button class="btn ghost" onclick="familyStopVoice()">■ Stop</button><button class="btn primary" onclick="familySpeak('Hello ${escapeHtml(state.profile?.name||'learner')}. Your selected Study Tracker voice is ready.')">▶ Test voice</button></div></section><section class="card"><div class="card-title"><h3>Family access</h3><span>Learner role</span></div><div class="setting-row"><span>Your unique learner ID</span><strong class="copy-id">${escapeHtml(id)}</strong></div><p class="task-meta">A Parent/Admin cannot be added with this permanent ID. Enter their temporary, single-use family code below.</p><label>Family linking code<input id="familyCodeInput" maxlength="12" placeholder="FAM-XXXXXX"></label><div class="modal-actions"><button class="btn primary" onclick="joinFamilyCode()">Link Parent/Admin</button></div>${linked?'<p class="family-linked">✓ This learner is linked to a Parent/Admin.</p>':''}</section><section class="card"><div class="card-title"><h3>Activity privacy</h3><span>On this app only</span></div><p class="task-meta">Tracks focused Study Tracker time, idle time, section visits and screen changes. It never records keystrokes or activity outside this application.</p><div class="setting-row"><span>Today active</span><strong>${formatDuration(activityDay()?.activeMs)}</strong></div><div class="setting-row"><span>Today screen changes</span><strong>${activityDay()?.viewChanges||0}</strong></div></section>`}
window.joinFamilyCode=()=>{const code=field('familyCodeInput').value.trim().toUpperCase(),invite=familyData.invites.find(i=>i.code===code&&i.expiresAt>Date.now()&&!i.used);if(!invite)return toast('Code is invalid or expired');const userId=familyId();if(!familyData.links.some(l=>l.userId===userId))familyData.links.push({userId,parentId:invite.parentId,userName:state.profile.name,linkedAt:new Date().toISOString()});invite.used=true;saveFamily();render();toast('Parent/Admin linked successfully')};
function familyOnBriefing(){setTimeout(()=>{const actions=document.querySelector('.briefing .modal-actions');if(!actions)return;const b=document.createElement('button');b.type='button';b.className='btn ghost';b.textContent='🔊 Read aloud';b.onclick=familySpeakBriefing;actions.prepend(b);if(familyData.settings.autoBriefing)familySpeakBriefing()},650)}
window.familyOnAppShown=()=>{if(isParentSession()){document.body.classList.add('parent-mode');setTimeout(renderParentPortal,50)}else{document.body.classList.remove('parent-mode');startActivityTracking();familyOnBriefing()}};
window.generateFamilyCode=()=>{familyData.invites=familyData.invites.filter(i=>i.expiresAt>Date.now()&&!i.used);const code=`FAM-${Math.random().toString(36).slice(2,8).toUpperCase()}`;familyData.invites.push({code,parentId:familyData.admin.id,expiresAt:Date.now()+15*60000,used:false});saveFamily();renderParentPortal();toast('Single-use code generated')};
window.unlinkFamilyUser=id=>{if(!confirm('Unlink this learner from the Parent account?'))return;familyData.links=familyData.links.filter(l=>l.userId!==id);saveFamily();renderParentPortal()};
window.clearLearnerActivity=id=>{if(!confirm('Permanently clear this learner activity history?'))return;delete familyData.activity[id];saveFamily();renderParentPortal()};
window.familyParentLogout=()=>{sessionStorage.removeItem(FAMILY_SESSION);parentWorkspaceMode=false;location.reload()};
window.familyOpenLearnerWorkspace=()=>{parentWorkspaceMode=true;document.body.classList.remove('parent-mode');viewName='dashboard';render();const bar=document.createElement('div');bar.className='parent-access-bar';bar.innerHTML='<strong>Parent/Admin access</strong><span>Managing the linked learner workspace</span><button onclick="familyReturnToPortal()">Return to Parent Portal</button>';document.body.appendChild(bar)};
window.familyReturnToPortal=()=>{parentWorkspaceMode=false;document.querySelector('.parent-access-bar')?.remove();document.body.classList.add('parent-mode');renderParentPortal()};
function activitySummary(id){const a=familyData.activity[id]||{days:{}},entries=Object.entries(a.days).sort((x,y)=>y[0].localeCompare(x[0])),todayData=a.days[today()]||{},week=entries.slice(0,7).reduce((n,[,d])=>n+(d.activeMs||0),0);return {a,entries,todayData,week}}
window.renderParentPortal=()=>{const links=familyData.links,{a,entries,todayData,week}=activitySummary(links[0]?.userId),selected=links[0];view.innerHTML=`${head(`Parent Dashboard`,`Signed in as ${escapeHtml(familyData.admin?.name||'Parent/Admin')}`,`<button class="btn ghost" onclick="familyParentLogout()">Sign out</button>`)}<div class="grid stats"><div class="stat"><div><small>Active today</small><strong>${formatDuration(todayData.activeMs)}</strong></div></div><div class="stat"><div><small>Idle today</small><strong>${formatDuration(todayData.idleMs)}</strong></div></div><div class="stat"><div><small>Seven-day study</small><strong>${formatDuration(week)}</strong></div></div><div class="stat"><div><small>Screen changes</small><strong>${todayData.viewChanges||0}</strong></div></div></div><div class="grid parent-grid"><section class="card"><div class="card-title"><h3>Linked learners</h3><span>${links.length}/5</span></div>${links.length?links.map(l=>`<div class="learner-row"><span><strong>${escapeHtml(l.userName)}</strong><small>${escapeHtml(l.userId)}</small></span><button class="mini-btn" onclick="unlinkFamilyUser('${l.userId}')">×</button></div>`).join(''):'<div class="empty">No learner linked yet.</div>'}<div class="invite-box">${familyData.invites.filter(i=>!i.used&&i.expiresAt>Date.now()).map(i=>`<strong>${i.code}</strong><small>Expires in ${Math.max(1,Math.ceil((i.expiresAt-Date.now())/60000))} minutes</small>`).join('')||'<small>Generate a temporary code, then enter it in the learner’s Settings.</small>'}<button class="btn primary" onclick="generateFamilyCode()">Generate linking code</button></div></section><section class="card"><div class="card-title"><h3>Recent activity</h3><span>${selected?escapeHtml(selected.userName):'No learner'}</span></div>${entries.length?`<div class="activity-table">${entries.slice(0,14).map(([date,d])=>`<div><span>${date}</span><b>${formatDuration(d.activeMs)}</b><small>${d.viewChanges||0} screen changes</small></div>`).join('')}</div>`:'<div class="empty">Activity appears after the learner uses the tracker.</div>'}</section><section class="card span-2"><div class="card-title"><h3>Section usage today</h3><span>Focused time only</span></div><div class="usage-bars">${Object.entries(todayData.views||{}).sort((a,b)=>b[1]-a[1]).map(([name,ms])=>`<div><span>${escapeHtml(name)}</span><div class="bar"><i style="width:${Math.min(100,Math.max(4,ms/(todayData.activeMs||1)*100))}%"></i></div><b>${formatDuration(ms)}</b></div>`).join('')||'<div class="empty">No focused usage today.</div>'}</div></section></div><div class="parent-actions">${selected?'<button class="btn primary" onclick="familyOpenLearnerWorkspace()">Manage learner workspace</button><button class="btn danger" onclick="clearLearnerActivity(\''+selected.userId+'\')">Clear activity history</button>':''}</div>`}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-auth-mode]').forEach(b=>b.onclick=()=>{const parent=b.dataset.authMode==='parent';loginForm.classList.toggle('hidden',parent);parentLoginForm.classList.toggle('hidden',!parent);if(parent){const setup=!familyData.admin;parentAuthTitle.textContent=setup?'Create Parent/Admin':'Parent access';parentAuthCopy.textContent=setup?'Create the protected Parent account for this device.':'Use your separate Parent/Admin credentials to monitor linked learners.';parentNameLabel.classList.toggle('hidden',!setup);parentLoginButton.firstChild.textContent=setup?'Create Parent Account ':'Open Parent Portal '}});parentLoginForm.onsubmit=async e=>{e.preventDefault();const username=parentId.value.trim(),pin=parentPin.value,name=parentName.value.trim();if(!familyData.admin){if(!name)return toast('Parent name is required');const salt=uid()+uid();familyData.admin={id:`parent-${uid()}`,name,username,salt,hash:await familyHash(pin,salt),createdAt:new Date().toISOString()};saveFamily()}else{const hash=await familyHash(pin,familyData.admin.salt);if(username!==familyData.admin.username||hash!==familyData.admin.hash)return toast('Incorrect Parent/Admin credentials')}sessionStorage.setItem(FAMILY_SESSION,'parent');showApp()};const baseSettings=settings;settings=()=>baseSettings().replace(/<\/div>$/,familySettingsCards()+'</div>');const baseSetView=window.setView;window.setView=n=>{trackFamilyView(n);return baseSetView(n)};document.querySelector('#modal').addEventListener('close',familyStopVoice);speechSynthesis?.getVoices()});
