/* Nestlyra Focus Groups: account-neutral connections, aggregate progress,
   group messaging, and limited record-level collaboration. */
const GROUPS_SCHEMA_FILE='supabase-groups-migration.sql';
const GROUP_INVITE_MINUTES=15,GROUP_MESSAGE_LIMIT=2000;
const GROUP_TYPES=[['study','Study group'],['exam','Exam group'],['certification','Certification group'],['accountability','Accountability group'],['family','Family group']];
const GROUP_ROLES=[['member','Member'],['contributor','Contributor'],['observer','Observer']];
let groupState={user:null,groups:[],selectedId:'',members:[],snapshots:[],records:[],messages:[],participants:new Map(),activeInvites:{},schemaReady:null,loading:false,messageGroupId:'',subscription:null,badgeSubscription:null,lastPublish:0};

window.groupReset=()=>{
  try{if(groupState.subscription&&sb)sb.removeChannel(groupState.subscription);if(groupState.badgeSubscription&&sb)sb.removeChannel(groupState.badgeSubscription)}catch{}
  groupState={user:null,groups:[],selectedId:'',members:[],snapshots:[],records:[],messages:[],participants:new Map(),activeInvites:{},schemaReady:null,loading:false,messageGroupId:'',subscription:null,badgeSubscription:null,lastPublish:0};
};

function groupMissingSchema(error){return /could not find the function|does not exist|schema cache|relation .*group_/i.test(error?.message||'')}
function groupRoleLabel(role='member'){return ({owner:'Owner',admin:'Admin',contributor:'Contributor',member:'Member',observer:'Observer'})[role]||role}
function groupTypeLabel(kind='study'){return GROUP_TYPES.find(([value])=>value===kind)?.[1]||'Group'}
function groupCanManage(group=groupState.groups.find(item=>item.group_id===groupState.selectedId)){return ['owner','admin'].includes(group?.viewer_role)}
function groupCanEdit(group=groupState.groups.find(item=>item.group_id===groupState.selectedId)){return ['owner','admin','contributor'].includes(group?.viewer_role)&&group?.group_mode==='limited'}
async function groupCurrentUser(){if(!sb)return null;const {data,error}=await sb.auth.getUser();if(error)return null;return data?.user||null}

window.groupEnsureProfile=async user=>{
  if(!sb||!user)return null;
  const displayName=user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'Nestlyra user';
  const {data,error}=await sb.rpc('group_ensure_profile',{p_display_name:displayName});
  if(error){if(groupMissingSchema(error)){groupState.schemaReady=false;return {user_id:user.id,display_name:displayName,pending_migration:true}}throw error}
  groupState.schemaReady=true;groupState.user=user;return Array.isArray(data)?data[0]:data;
};

window.copyGroupsDatabaseFix=async()=>{
  try{const response=await fetch(`./${GROUPS_SCHEMA_FILE}`,{cache:'no-store'});if(!response.ok)throw Error('Migration file unavailable');await navigator.clipboard.writeText(await response.text());toast('Groups migration SQL copied')}catch(error){toast(error.message||'Download the migration SQL from the repository')}
};

function groupMigrationMarkup(){return `<div class="group-migration card"><span>!</span><div><h2>One-time Groups database update required</h2><p>The application code is ready, but Supabase must receive the backward-compatible Groups migration before cloud invitations, messaging and permissions can run.</p><ul><li>Existing accounts stay valid.</li><li>Existing Parent/Learner links become Family groups.</li><li>Private tracker records stop being exposed to observers.</li></ul><div class="modal-actions"><button class="btn primary" onclick="copyGroupsDatabaseFix()">Copy migration SQL</button><a class="btn ghost" href="${GROUPS_SCHEMA_FILE}" download>Download SQL</a><button class="btn ghost" onclick="groupBoot(true)">Check again</button></div></div></div>`}

window.groupsView=()=>{
  setTimeout(()=>groupBoot(false));
  return head('Groups','Connect study partners, accountability members or family observers without changing account type',`<button class="btn ghost" onclick="groupJoinModal()">Join group</button><button class="btn primary" onclick="groupCreateModal()">+ Create group</button>`)+`<div id="groupsRoot" class="groups-root"><div class="empty">Loading your secure groups…</div></div>`;
};

window.groupBoot=async(force=false)=>{
  const root=document.querySelector('#groupsRoot');
  if(groupState.loading&&!force)return;
  groupState.loading=true;
  try{
    const user=await groupCurrentUser();groupState.user=user;
    if(!user){groupState.schemaReady=null;if(root)root.innerHTML=`<div class="group-cloud-required card"><span>☁</span><h2>Cloud account required</h2><p>Groups connect people across devices, so sign in with email or Google. Your private workspace can still remain local-first.</p><button class="btn primary" onclick="signOut()">Open sign in</button></div>`;return}
    await groupEnsureProfile(user);
    const {data,error}=await sb.rpc('group_list');
    if(error){if(groupMissingSchema(error)){groupState.schemaReady=false;if(root)root.innerHTML=groupMigrationMarkup();return}throw error}
    groupState.schemaReady=true;groupState.groups=data||[];
    if(!groupState.groups.some(item=>item.group_id===groupState.selectedId))groupState.selectedId=groupState.groups[0]?.group_id||'';
    if(groupState.selectedId)await groupLoadDetails(groupState.selectedId,false);
    if(root)groupPaint();
    groupPublishProgress();groupRefreshBadge();
  }catch(error){if(root)root.innerHTML=`<div class="empty"><h2>Groups could not load</h2><p>${escapeHtml(error.message||'Unknown error')}</p><button class="btn primary" onclick="groupBoot(true)">Try again</button></div>`}
  finally{groupState.loading=false}
};

async function groupLoadDetails(groupId,repaint=true){
  groupState.selectedId=groupId;
  const [members,snapshots,records]=await Promise.all([
    sb.rpc('group_members_list',{p_group_id:groupId}),
    sb.from('group_progress_snapshots').select('*').eq('group_id',groupId).order('last_updated',{ascending:false}),
    sb.from('group_shared_records').select('*').eq('group_id',groupId).is('deleted_at',null).order('updated_at',{ascending:false})
  ]);
  if(members.error||snapshots.error||records.error)throw members.error||snapshots.error||records.error;
  groupState.members=members.data||[];groupState.snapshots=snapshots.data||[];groupState.records=records.data||[];
  if(repaint)groupPaint();
}

window.groupSelect=async id=>{try{await groupLoadDetails(id);groupState.messageGroupId=id}catch(error){toast(error.message||'Group could not open')}};

function groupSidebar(){
  return `<aside class="group-sidebar card"><div class="card-title"><h3>Your groups</h3><span>${groupState.groups.length}</span></div><div class="group-list">${groupState.groups.map(item=>`<button class="group-list-item ${item.group_id===groupState.selectedId?'active':''}" onclick="groupSelect('${item.group_id}')"><span>${({study:'◫',exam:'◇',certification:'✓',accountability:'⌁',family:'⌂'})[item.group_kind]||'◎'}</span><span><strong>${escapeHtml(item.group_name)}</strong><small>${groupTypeLabel(item.group_kind)} · ${item.member_count} members</small></span>${Number(item.unread_count||0)?`<i>${item.unread_count}</i>`:''}</button>`).join('')||'<div class="empty compact-empty">No groups yet.</div>'}</div><div class="group-sidebar-actions"><button class="btn primary" onclick="groupCreateModal()">Create group</button><button class="btn ghost" onclick="groupJoinModal()">Join with code</button></div></aside>`;
}

function groupProgressMarkup(){
  const byUser=new Map();
  groupState.snapshots.forEach(snapshot=>{if(!byUser.has(snapshot.user_id))byUser.set(snapshot.user_id,[]);byUser.get(snapshot.user_id).push(snapshot)});
  return `<section class="card group-progress"><div class="card-title"><h3>Shared progress</h3><span>Aggregates only</span></div><div class="group-progress-grid">${groupState.members.map(member=>{const rows=byUser.get(member.user_id)||[],overallRow=rows.find(row=>row.module_type==='overall'),presence=overallRow?.last_seen?Date.now()-new Date(overallRow.last_seen).getTime()<75000:false;return `<article><header><span class="group-avatar">${escapeHtml((member.display_name||'U')[0].toUpperCase())}</span><span><strong>${escapeHtml(member.display_name||'Member')}</strong><small>${groupRoleLabel(member.role)} · <i class="presence ${presence?'online':''}">${presence?'● Online':'○ '+(overallRow?.last_seen?'Last seen '+new Date(overallRow.last_seen).toLocaleString():'No update')}</i></small></span></header>${member.share_progress===false?'<p class="group-private">Progress sharing is off.</p>':rows.length?`<div class="group-snapshot-list">${rows.slice(0,6).map(row=>`<div><span>${escapeHtml(row.module_type.replaceAll('_',' '))}</span><b>${Math.round(Number(row.progress_percent||0))}%</b><small>${Number(row.completed_count||0)}/${Number(row.total_count||0)}</small></div>`).join('')}</div>`:'<p class="group-private">No progress published yet.</p>'}</article>`}).join('')}</div><p class="settings-note">Nestlyra shares percentages, counts, study minutes and last update—not subject names, notes, resumes, job applications, mistake logs or document contents.</p></section>`;
}

function groupMembersMarkup(group){
  const manage=groupCanManage(group);
  return `<section class="card group-members"><div class="card-title"><h3>Members & permissions</h3><span>${groupState.members.length}</span></div><div class="group-member-list">${groupState.members.map(member=>`<div><span class="group-avatar">${escapeHtml((member.display_name||'U')[0].toUpperCase())}</span><span><strong>${escapeHtml(member.display_name||'Member')}</strong><small>${groupRoleLabel(member.role)}${member.user_id===groupState.user?.id?' · You':''}</small></span>${manage&&member.role!=='owner'?`<select aria-label="Role for ${escapeHtml(member.display_name)}" onchange="groupChangeRole('${member.user_id}',this.value)">${GROUP_ROLES.map(([value,label])=>`<option value="${value}" ${member.role===value?'selected':''}>${label}</option>`).join('')}<option value="admin" ${member.role==='admin'?'selected':''}>Admin</option></select><button class="mini-btn" title="Remove member" onclick="groupRemoveMember('${member.user_id}')">×</button>${group.viewer_role==='owner'?`<button class="mini-btn transfer-owner" title="Transfer ownership" onclick="groupTransferOwner('${member.user_id}')">⇄</button>`:''}`:''}</div>`).join('')}</div>${manage?groupInviteMarkup(group):''}</section>`;
}

function groupInviteMarkup(group){
  const invite=groupState.activeInvites[group.group_id],valid=invite&&invite.expiresAt>Date.now();
  return `<div class="group-invite-box">${valid?`<div><small>Current valid code</small><strong>${escapeHtml(invite.code)}</strong><span>Expires ${new Date(invite.expiresAt).toLocaleTimeString()}</span></div>`:'<div><small>Invite a member</small><strong>No active code</strong><span>A replacement immediately invalidates the old code.</span></div>'}<button class="btn primary" onclick="groupInviteModal('${group.group_id}')">${valid?'Replace code':'Generate code'}</button></div>`;
}

function groupSharedMarkup(group){
  const editable=groupCanEdit(group);
  if(group.group_mode!=='limited')return `<section class="card group-shared"><div class="card-title"><h3>Shared records</h3><span>View-only group</span></div><div class="empty compact-empty">This group intentionally shares progress and messages only. An owner can use a separate limited co-edit group for shared tasks, goals, plans or short notes.</div></section>`;
  return `<section class="card group-shared"><div class="card-title"><h3>Shared records</h3><span>Record-level co-edit</span></div>${editable?`<div class="group-shared-actions">${['task','goal','plan','note'].map(type=>`<button class="btn ghost" onclick="groupSharedModal('${type}')">+ ${type}</button>`).join('')}</div>`:''}<div class="group-record-list">${groupState.records.map(record=>`<article><span>${({task:'✓',goal:'◇',plan:'▦',note:'✎'})[record.record_type]||'•'}</span><button onclick="groupSharedModal('${record.record_type}','${record.id}')"><strong>${escapeHtml(record.title)}</strong><small>${escapeHtml(record.details||'No details')}${record.due_date?` · ${record.due_date}`:''}</small></button><i>v${record.version}</i>${editable?`<button class="mini-btn" onclick="groupDeleteShared('${record.id}')">×</button>`:''}</article>`).join('')||'<div class="empty compact-empty">No shared records yet.</div>'}</div><p class="settings-note">Saves use version checks. If two people edit the same record, Nestlyra preserves the newer version and asks the other person to reload instead of silently overwriting it.</p></section>`;
}

function groupDetail(){
  const group=groupState.groups.find(item=>item.group_id===groupState.selectedId);if(!group)return `<section class="group-welcome card"><span>◎</span><h2>Create your first group</h2><p>Use one account for personal tracking, then connect only the people and progress you choose.</p><div><button class="btn primary" onclick="groupCreateModal()">Create group</button><button class="btn ghost" onclick="groupJoinModal()">Join with code</button></div></section>`;
  return `<main class="group-detail"><header class="group-detail-head"><div><span class="eyebrow">${escapeHtml(groupTypeLabel(group.group_kind).toUpperCase())}</span><h2>${escapeHtml(group.group_name)}</h2><p>${group.group_mode==='limited'?'Limited co-edit for shared records':'View-only progress and accountability'} · You are ${groupRoleLabel(group.viewer_role)}</p></div><div><button class="btn primary" onclick="groupOpenMessages('${group.group_id}')">✉ Messages</button>${group.viewer_role==='owner'?`<button class="btn danger" onclick="groupDelete('${group.group_id}')">Delete group</button>`:`<button class="btn ghost" onclick="groupLeave('${group.group_id}')">Leave</button>`}</div></header>${groupProgressMarkup()}<div class="group-two-column">${groupMembersMarkup(group)}${groupSharedMarkup(group)}</div></main>`;
}
function groupPaint(){const root=document.querySelector('#groupsRoot');if(root)root.innerHTML=`<div class="group-shell">${groupSidebar()}${groupDetail()}</div>`}

window.groupCreateModal=()=>modal(`<h2>Create a Nestlyra group</h2><p class="task-meta">Your account stays personal. The group receives only permissions and aggregate information defined below.</p><div class="form-grid"><label class="full">Group name<input id="groupName" maxlength="80" placeholder="OSCP accountability group"></label><label>Group type<select id="groupKind">${GROUP_TYPES.map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></label><label>Collaboration<select id="groupMode"><option value="view">View-only progress</option><option value="limited">Limited co-edit</option></select></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="groupCreate()">Create group</button></div>`);
window.groupCreate=async()=>{const name=field('groupName').value.trim();if(!name)return toast('Enter a group name');const {data,error}=await sb.rpc('group_create',{p_name:name,p_kind:field('groupKind').value,p_mode:field('groupMode').value});if(error)return toast(error.message);closeModal();groupState.selectedId=Array.isArray(data)?data[0]?.group_id:data?.group_id;await groupBoot(true);toast('Group created')};
window.groupJoinModal=()=>{if(!cloudUser)return toast('Sign in with a cloud account to join a group');modal(`<h2>Join a group</h2><p>Enter the current single-use invitation code from a group owner or admin.</p><label>Invitation code<input id="groupJoinCode" maxlength="11" placeholder="NEST-XXXXXX" oninput="this.value=this.value.toUpperCase()"></label><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="groupJoin()">Join group</button></div>`)};
window.groupJoin=async()=>{const code=field('groupJoinCode').value.trim().toUpperCase();const {data,error}=await sb.rpc('group_redeem_invite',{p_code:code});if(error)return toast(error.message);closeModal();groupState.selectedId=Array.isArray(data)?data[0]?.group_id:data?.group_id;await groupBoot(true);toast('Group connected')};
window.groupInviteModal=(groupId=groupState.selectedId)=>{if(!groupId)return;modal(`<h2>Generate group invitation</h2><p>The code expires after ${GROUP_INVITE_MINUTES} minutes and works once. Generating another code immediately invalidates the previous one for this group.</p><label>Permission for the new member<select id="groupInviteRole">${GROUP_ROLES.map(([value,label])=>`<option value="${value}">${label}${value==='observer'?' — read-only':''}</option>`).join('')}</select></label><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="groupGenerateInvite('${groupId}')">Generate code</button></div>`)};
window.groupGenerateInvite=async groupId=>{const code=`NEST-${Math.random().toString(36).slice(2,8).toUpperCase()}`,role=field('groupInviteRole').value;const {data,error}=await sb.rpc('group_generate_invite',{p_group_id:groupId,p_code:code,p_role:role});if(error)return toast(error.message);const row=Array.isArray(data)?data[0]:data;groupState.activeInvites[groupId]={code,expiresAt:new Date(row.expires_at).getTime(),role};closeModal();groupPaint();toast('One valid invitation code generated')};
window.groupChangeRole=async(userId,role)=>{const {error}=await sb.rpc('group_change_member_role',{p_group_id:groupState.selectedId,p_user_id:userId,p_role:role});if(error)return toast(error.message);await groupLoadDetails(groupState.selectedId);toast('Permission updated')};
window.groupTransferOwner=async userId=>{if(!confirm('Transfer group ownership to this member? You will become an Admin.'))return;const {error}=await sb.rpc('group_transfer_ownership',{p_group_id:groupState.selectedId,p_user_id:userId});if(error)return toast(error.message);await groupBoot(true);toast('Ownership transferred')};
window.groupRemoveMember=async userId=>{if(!confirm('Remove this member from the group? Access ends immediately.'))return;const {error}=await sb.rpc('group_remove_member',{p_group_id:groupState.selectedId,p_user_id:userId});if(error)return toast(error.message);await groupBoot(true);toast('Member removed')};
window.groupLeave=async groupId=>{if(!confirm('Leave this group? You will immediately lose its messages and shared records.'))return;const {error}=await sb.rpc('group_leave',{p_group_id:groupId});if(error)return toast(error.message);groupState.selectedId='';await groupBoot(true)};
window.groupDelete=async groupId=>{if(!confirm('Delete this group for every member? This cannot be undone.'))return;const {error}=await sb.rpc('group_delete',{p_group_id:groupId});if(error)return toast(error.message);groupState.selectedId='';await groupBoot(true);toast('Group deleted')};

window.groupSharedModal=(type,id='')=>{const record=groupState.records.find(item=>item.id===id);modal(`<h2>${record?'Edit':'Add shared'} ${escapeHtml(type)}</h2><div class="form-grid"><label class="full">Title<input id="groupRecordTitle" maxlength="160" value="${escapeHtml(record?.title||'')}"></label><label class="full">Short details<textarea id="groupRecordDetails" maxlength="2000" rows="5">${escapeHtml(record?.details||'')}</textarea></label><label>Due date<input id="groupRecordDue" type="date" value="${record?.due_date||''}"></label></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="groupSaveShared('${type}','${id}',${Number(record?.version||0)})">Save</button></div>`)};
window.groupSaveShared=async(type,id,version)=>{const title=field('groupRecordTitle').value.trim();if(!title)return toast('Enter a title');const {error}=await sb.rpc('group_save_shared_record',{p_id:id||null,p_group_id:groupState.selectedId,p_type:type,p_title:title,p_details:field('groupRecordDetails').value.trim(),p_due_date:field('groupRecordDue').value||null,p_expected_version:version});if(error)return toast(/version conflict/i.test(error.message)?'Someone updated this record first. Reload and try again.':error.message);closeModal();await groupLoadDetails(groupState.selectedId);toast('Shared record saved')};
window.groupDeleteShared=async id=>{if(!confirm('Delete this shared record?'))return;const {error}=await sb.rpc('group_delete_shared_record',{p_id:id,p_group_id:groupState.selectedId});if(error)return toast(error.message);await groupLoadDetails(groupState.selectedId)};

window.groupUpdateSharing=async(key,value)=>{if(!groupState.selectedId)return toast('Open a group first');const current=groupState.groups.find(item=>item.group_id===groupState.selectedId),progress=key==='progress'?value:current?.share_progress!==false,activity=key==='activity'?value:current?.share_activity!==false;const {error}=await sb.rpc('group_update_sharing',{p_group_id:groupState.selectedId,p_share_progress:progress,p_share_activity:activity});if(error)return toast(error.message);await groupBoot(true);toast('Group privacy updated')};

window.groupSettingsCard=()=>{
  const group=groupState.groups.find(item=>item.group_id===groupState.selectedId),cloud=Boolean(cloudUser);
  return `<section class="card"><div class="card-title"><h3>Group connections</h3><span>${cloud?`${groupState.groups.length} joined`:'Cloud required'}</span></div><p class="task-meta">One account can create or join Study, Exam, Certification, Accountability and Family groups. Parent/child is now an optional observer relationship—not a permanent login role.</p>${cloud?`<label class="workspace-switcher">Privacy group<select onchange="groupState.selectedId=this.value;groupBoot(true)">${groupState.groups.map(item=>`<option value="${item.group_id}" ${item.group_id===groupState.selectedId?'selected':''}>${escapeHtml(item.group_name)}</option>`).join('')}</select></label>${group?`<div class="setting-row"><span>Share aggregate progress</span><button class="toggle ${group.share_progress!==false?'on':''}" onclick="groupUpdateSharing('progress',${group.share_progress===false})"></button></div><div class="setting-row"><span>Share aggregate activity</span><button class="toggle ${group.share_activity!==false?'on':''}" onclick="groupUpdateSharing('activity',${group.share_activity===false})"></button></div>`:''}<div class="modal-actions"><button class="btn ghost" onclick="groupJoinModal()">Join with code</button><button class="btn primary" onclick="setView('groups')">Manage groups</button></div>`:'<div class="modal-actions"><button class="btn primary" onclick="signOut()">Sign in with cloud account</button></div>'}<p class="settings-note">Private syllabus titles, notes, resumes, applications, documents and mistake logs are never published to a group.</p></section>`;
};

function groupAggregateRows(){
  const topics=allTopics(),completedTopics=topics.filter(item=>item.status==='completed').length,studyMinutes=(state.activity||[]).reduce((sum,item)=>sum+Number(item.minutes||0),0),day=activityDay()||{},mocks=state.mockTests||[],mockAverage=mocks.length?mocks.reduce((sum,item)=>sum+(Number(item.score||0)/Math.max(1,Number(item.total||100))*100),0)/mocks.length:0;
  const rows=[{module_type:'overall',completed_count:completedTopics,total_count:topics.length,progress_percent:topics.length?completedTopics/topics.length*100:0,study_minutes:studyMinutes,mock_average:mockAverage}];
  const add=(type,items,done)=>{if(!items)return;const complete=items.filter(done).length;rows.push({module_type:type,completed_count:complete,total_count:items.length,progress_percent:items.length?complete/items.length*100:0,study_minutes:0,mock_average:0})};
  add('tasks',state.tasks||[],item=>item.status==='completed');
  add('certifications',state.certifications||[],item=>item.status==='Completed');
  add('exams',state.examPlans||[],item=>Number(item.progress||0)>=100);
  add('goals',state.goals||[],item=>Number(item.progress||0)>=100);
  add('habits',state.habits||[],item=>(item.completedDates||[]).includes(today()));
  return rows.map(row=>({...row,active_minutes:Math.round(Number(day.activeMs||0)/60000),screen_changes:Number(day.viewChanges||0),last_seen:new Date().toISOString()}));
}

window.groupPublishProgress=async(force=false)=>{
  if(!sb||!cloudUser||groupState.schemaReady===false||(!force&&Date.now()-groupState.lastPublish<30000))return;
  groupState.lastPublish=Date.now();
  try{
    if(!groupState.groups.length){const {data,error}=await sb.rpc('group_list');if(error){if(groupMissingSchema(error))groupState.schemaReady=false;return}groupState.groups=data||[]}
    const rows=groupAggregateRows();
    for(const group of groupState.groups){if(group.share_progress===false&&group.share_activity===false)continue;for(const row of rows){const payload={...row};if(group.share_progress===false){payload.completed_count=0;payload.total_count=0;payload.progress_percent=0;payload.study_minutes=0;payload.mock_average=0}if(group.share_activity===false){payload.active_minutes=0;payload.screen_changes=0;payload.last_seen=null}await sb.rpc('group_publish_snapshot',{p_group_id:group.group_id,p_snapshot:payload})}}
  }catch(error){console.warn('Group progress projection:',error.message)}
};

function groupMessageMarkup(message){const own=message.sender_id===groupState.user?.id,person=groupState.participants.get(message.sender_id);return `<article class="family-message ${own?'own':''}"><div class="family-message-meta"><strong>${own?'You':escapeHtml(person?.display_name||'Group member')}</strong><span>${new Date(message.created_at).toLocaleString()}${message.edited_at?' · edited':''}</span></div><p>${escapeHtml(message.body).replace(/\n/g,'<br>')}</p>${own?`<div class="family-message-actions"><button onclick="groupMessageEdit('${message.id}')">Edit</button><button onclick="groupMessageDelete('${message.id}')">Delete</button></div>`:''}</article>`}
window.groupMessagingView=()=>{setTimeout(()=>groupMessagingBoot());return head('Group messages','Private text conversations inside every group you joined',`<button class="btn ghost" onclick="setView('groups')">Manage groups</button>`)+`<div id="groupMessagingRoot" class="family-chat-root"><div class="empty">Opening group conversations…</div></div>`};
window.groupOpenMessages=id=>{groupState.messageGroupId=id;viewName='messages';render()};
window.groupMessagingBoot=async()=>{
  const root=document.querySelector('#groupMessagingRoot');if(!root)return;
  const user=await groupCurrentUser();if(!user){root.innerHTML='<div class="family-chat-empty"><span>☁</span><h3>Cloud account required</h3><p>Sign in with email or Google to use group messaging.</p></div>';return}
  groupState.user=user;const {data,error}=await sb.rpc('group_list');if(error){root.innerHTML=groupMissingSchema(error)?groupMigrationMarkup():`<div class="empty">${escapeHtml(error.message)}</div>`;return}groupState.groups=data||[];
  if(!groupState.groups.length){root.innerHTML='<div class="family-chat-empty"><span>✉</span><h3>No group conversations yet</h3><p>Create or join a group first.</p><button class="btn primary" onclick="setView(\'groups\')">Open Groups</button></div>';return}
  if(!groupState.groups.some(item=>item.group_id===groupState.messageGroupId))groupState.messageGroupId=groupState.groups[0].group_id;
  root.innerHTML=`<div class="family-chat-layout"><aside class="family-room-panel"><div class="family-room-heading"><div><strong>Groups</strong><small>Text only · 30-day retention</small></div></div><div class="family-room-list">${groupState.groups.map(item=>`<button class="family-room ${item.group_id===groupState.messageGroupId?'active':''}" onclick="groupMessageOpen('${item.group_id}')"><span class="family-room-avatar">${escapeHtml(item.group_name[0].toUpperCase())}</span><span><strong>${escapeHtml(item.group_name)}</strong><small>${item.member_count} members</small></span>${Number(item.unread_count||0)?`<i>${item.unread_count}</i>`:''}</button>`).join('')}</div></aside><section id="groupMessagePane" class="family-chat-pane"><div class="empty">Loading messages…</div></section></div>`;
  await groupMessageOpen(groupState.messageGroupId);
};
window.groupMessageOpen=async groupId=>{
  groupState.messageGroupId=groupId;const pane=document.querySelector('#groupMessagePane');if(!pane)return;
  pane.innerHTML='<div class="empty">Loading messages…</div>';
  const [members,messages]=await Promise.all([sb.rpc('group_members_list',{p_group_id:groupId}),sb.from('group_messages').select('id,group_id,sender_id,body,created_at,edited_at').eq('group_id',groupId).order('created_at',{ascending:true}).limit(300)]);
  if(members.error||messages.error){pane.innerHTML=`<div class="empty">${escapeHtml(members.error?.message||messages.error?.message)}</div>`;return}
  groupState.participants=new Map((members.data||[]).map(member=>[member.user_id,member]));groupState.messages=messages.data||[];
  const group=groupState.groups.find(item=>item.group_id===groupId);
  pane.innerHTML=`<header class="family-chat-header"><div><strong>${escapeHtml(group?.group_name||'Group')}</strong><small>${[...groupState.participants.values()].map(member=>escapeHtml(member.display_name)).join(', ')}</small></div><span>${groupState.participants.size} members</span></header><div class="family-retention-banner"><span>♻</span><p><strong>Private text only.</strong> Messages are permanently deleted after 30 days and may be removed earlier if database use reaches 75%.</p></div><div id="groupMessageList" class="family-message-list">${groupState.messages.length?groupState.messages.map(groupMessageMarkup).join(''):'<div class="family-chat-empty compact"><span>✉</span><h3>Start the conversation</h3><p>Send a progress update, reminder or question.</p></div>'}</div><div class="family-compose"><textarea id="groupMessageInput" maxlength="${GROUP_MESSAGE_LIMIT}" rows="2" placeholder="Write a message…" oninput="groupMessageCount(this)" onkeydown="groupMessageKey(event)"></textarea><div><small id="groupMessageCounter">0 / ${GROUP_MESSAGE_LIMIT}</small><button class="btn primary" onclick="groupMessageSend()">Send</button></div></div>`;
  await sb.rpc('group_mark_read',{p_group_id:groupId});groupMessageSubscribe(groupId);groupRefreshBadge();const list=document.querySelector('#groupMessageList');if(list)list.scrollTop=list.scrollHeight;
};
window.groupMessageCount=input=>{const counter=document.querySelector('#groupMessageCounter');if(counter)counter.textContent=`${input.value.length} / ${GROUP_MESSAGE_LIMIT}`};
window.groupMessageKey=event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();groupMessageSend()}};
window.groupMessageSend=async()=>{const input=field('groupMessageInput'),body=input.value.trim();if(!body)return;const {error}=await sb.from('group_messages').insert({group_id:groupState.messageGroupId,sender_id:groupState.user.id,body});if(error)return toast(error.message);input.value='';await sb.rpc('cleanup_group_messages');await groupMessageOpen(groupState.messageGroupId)};
window.groupMessageEdit=async id=>{const message=groupState.messages.find(item=>item.id===id),body=prompt('Edit message:',message?.body||'')?.trim();if(!body)return;const {error}=await sb.from('group_messages').update({body}).eq('id',id);if(error)return toast(error.message);await groupMessageOpen(groupState.messageGroupId)};
window.groupMessageDelete=async id=>{if(!confirm('Delete this message permanently?'))return;const {error}=await sb.from('group_messages').delete().eq('id',id);if(error)return toast(error.message);await groupMessageOpen(groupState.messageGroupId)};
function groupMessageSubscribe(groupId){if(groupState.subscription)sb.removeChannel(groupState.subscription);groupState.subscription=sb.channel(`group-messages-${groupId}`).on('postgres_changes',{event:'*',schema:'public',table:'group_messages',filter:`group_id=eq.${groupId}`},()=>groupMessageOpen(groupId)).subscribe()}
function groupPaintBadge(total){const visible=Number(total)>0&&familyData.settings.messageNotifications!==false;document.querySelectorAll('#messageBadge,#floatingMessageBadge').forEach(badge=>{badge.textContent=Number(total)>99?'99+':String(total);badge.classList.toggle('hidden',!visible)})}
window.groupRefreshBadge=async()=>{const user=await groupCurrentUser();if(!user)return groupPaintBadge(0);const {data,error}=await sb.rpc('group_list');if(error)return;const total=(data||[]).reduce((sum,item)=>sum+Number(item.unread_count||0),0);groupPaintBadge(total);if(!groupState.badgeSubscription)groupState.badgeSubscription=sb.channel(`group-badge-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'group_messages'},payload=>{if(payload.new?.sender_id!==user.id&&familyData.settings.messageSound)try{familyMessageBeep()}catch{}setTimeout(groupRefreshBadge,100)}).subscribe()};

window.familyMessagingView=window.groupMessagingView;
window.familyOpenMessaging=()=>setView('messages');
window.familyMessagingRefreshBadge=window.groupRefreshBadge;
window.familyMessagingSettingsCard=()=>`<section class="card"><div class="card-title"><h3>Messaging & privacy</h3><span>Groups · text only</span></div><p class="task-meta">Messages are available to cloud accounts inside groups. Voice, video, files and public messaging remain disabled.</p><div class="setting-row"><span>Unread message badge</span><button class="toggle ${familyData.settings.messageNotifications?'on':''}" onclick="setFamilySetting('messageNotifications',!${familyData.settings.messageNotifications});render()"></button></div><div class="setting-row"><span>New message sound</span><button class="toggle ${familyData.settings.messageSound?'on':''}" onclick="setFamilySetting('messageSound',!${familyData.settings.messageSound});render()"></button></div><div class="retention-settings"><b>Automatic retention</b><span>Permanent deletion after 30 days</span><span>Oldest messages removed earlier at 75% database use</span></div><div class="modal-actions"><button class="btn primary" onclick="setView('messages')">Open messages</button></div></section>`;
window.familyManualSettingsCard=()=>`<section class="card"><div class="card-title"><h3>Help & user manual</h3><span>Complete guide</span></div><p class="task-meta">Read setup, modules, Calendar, Groups, permissions, invitations, messaging, storage and account-security guidance.</p><div class="modal-actions"><button class="btn ghost" onclick="loginFaqModal()">Login FAQ</button><button class="btn primary" onclick="setView('help')">Open full manual</button></div></section>`;
window.addMessagingToManual=html=>html;

function groupHelpView(){
  const sections=[
    ['setup','01','Account setup','One account works for personal tracking and every group.',`<ol><li>Use the single login form with email/password, Google, or a local name/PIN.</li><li>Email and Google accounts can sync across devices and use Groups. Local accounts remain on this browser and cannot collaborate across devices.</li><li>New accounts receive a five-module sample subject with five topics per module. Edit or delete it after learning the structure.</li><li>There is no permanent Parent or Learner account type. A person’s permissions come from each group they join.</li></ol>`],
    ['dashboard','02','Dashboard and daily briefing','See the current workspace without exposing it to group members.',`<ul><li>Dashboard cards summarize enabled modules, current progress and today’s plan.</li><li>The greeting popup can include overdue work, today’s tasks, upcoming topics and Job Tracker follow-ups.</li><li>Close it with ×, click outside, choose Start my day, or disable/configure it in Settings.</li><li>Voice can read the briefing using one of five profiles. Closing the popup cancels delayed speech.</li></ul>`],
    ['subjects','03','Subjects, modules and topics','Build personal course structures and completion progress.',`<ol><li>Create a subject, then add modules and topics.</li><li>Each topic supports Not started, In progress or Completed and an optional due date.</li><li>Subject progress is calculated from completed topics.</li><li>Groups receive only aggregate percentages and counts—not subject, module or topic names.</li></ol>`],
    ['modules','05','Navigation, presets and modules','Fit Nestlyra Focus to a child, learner, candidate or job seeker.',`<ul><li>Settings → Navigation & modules includes School/Child, Certification Preparation, Competitive Exam, Job Seeker, Daily Productivity and Custom presets.</li><li>Available sections include Subjects, Certifications, Exams, Mocks, Revision, Assignments, Resources, Practice, Projects, Tasks, Calendar, Notes, Habits, Goals, Interviews, Job Tracker, Study Timer and Groups.</li><li>Settings and Manual & FAQ are enabled by default but may be hidden from the sidebar.</li><li>The profile avatar always opens Settings. Every visible sidebar section has a ? button that opens its exact manual page.</li><li>Turning a module off hides it without deleting data. Module choices are saved per workspace.</li></ul>`],
    ['jobs','06','Job Tracker and browser extension','Preserve applications and disappearing job descriptions.',`<ul><li>Save company, role, status, dates, link, follow-up, contacts, notes and pasted JD text.</li><li>Attach a JD, tailored resume or cover letter later when editing an application.</li><li>The extension captures visible job details only after you click Capture and always opens a review draft before saving.</li><li>Install it by extracting <code>nestlyra-focus-job-capture.zip</code>, opening Chrome/Edge Extensions, enabling Developer mode and selecting Load unpacked.</li><li>Applications and documents remain private and are never included in group progress.</li></ul>`],
    ['storage','07','Documents and storage','Understand exactly where large files live.',`<ul><li>New JD, resume and cover-letter files are stored in this browser’s IndexedDB, up to 10 MB each.</li><li>New file bytes are not uploaded to Supabase Storage.</li><li>Legacy Supabase attachment paths remain download-compatible.</li><li>Google Drive connection is planned but is not enabled yet. No file is silently copied to another service.</li><li>Groups and messages do not support file, voice, image or video attachments in V1.</li></ul>`],
    ['settings','08','Settings and workspaces','Separate different goals while keeping one account.',`<ul><li>Use the avatar to open Settings even when the Settings sidebar item is hidden.</li><li>Settings covers profile, password, appearance, notifications, briefing, voice, modules, Groups, data transfer and deletion.</li><li>Create, rename, archive, switch or delete workspaces. Each workspace keeps its own module choices and tracking records.</li><li>Theme, text style, text size and login image can be customized after login; Nestlyra is the new-user default.</li></ul>`],
    ['groups','09','Groups, roles and invitations','Connect people without creating separate Parent accounts.',`<ul><li>Create a Study, Exam, Certification, Accountability or Family group, or join with a code.</li><li>Owner controls the group; Admin manages members; Contributor edits allowed shared records; Member participates; Observer is read-only.</li><li>One code is valid per group for 15 minutes and works once. Replacing it immediately revokes the previous code.</li><li>Existing Parent/Learner links are migrated into Family groups: the learner becomes Owner and existing parents become Observers.</li><li>A user may belong to multiple groups with a different permission in each.</li></ul>`],
    ['collaboration','10','Progress privacy and limited co-edit','Share useful signals without sharing private workspaces.',`<ul><li>View-only groups share aggregate progress, study minutes and last update.</li><li>Members can independently disable aggregate progress or activity sharing for a group.</li><li>Limited co-edit groups additionally support shared tasks, goals, plans and short notes.</li><li>Shared saves use version checks to prevent silent overwriting.</li><li>Private syllabi, notes, resumes, applications, documents and mistake logs remain local or in the user’s own storage.</li></ul>`],
    ['messaging','11','Group messaging and retention','Use private text chat with unread indicators.',`<ul><li>Open Messages from the floating envelope. A red counter indicates unread group messages.</li><li>Every current group member can read and send text up to 2,000 characters.</li><li>Messages are permanently deleted after 30 days. Senders can delete sooner and edit recent messages.</li><li>If the database reaches approximately 75% of the free quota, older messages may be removed sooner.</li><li>Removing a member immediately removes their access through Supabase RLS.</li></ul>`],
    ['transfer','12','Import and export','Transfer only the data intended by each feature.',`<ul><li>Subject JSON import/export contains subjects, modules, topics, statuses and topic dates only.</li><li>It excludes profile, settings, tasks, events, jobs, documents, activity, Groups and messages.</li><li>Job Tracker has a separate filtered CSV export that never contains attachment bytes.</li></ul>`],
    ['security','13','Security, sign out and deletion','Treat server policies as the real permission boundary.',`<ul><li>Supabase RLS—not frontend labels—controls group access, membership and edits.</li><li>Role changes use controlled database functions. Removed members lose access immediately.</li><li>A sole Owner must transfer ownership or delete a group before leaving.</li><li>Deleting an account removes authentication and personal tracker data. An owned group transfers when possible; otherwise it is deleted.</li><li>A deleted account cannot return through browser cache and must be created again.</li></ul>`],
    ['faq','14','Frequently asked questions','Quick answers for common Nestlyra Focus questions.',`<div class="faq-list"><details open><summary>Can one account be an observer and a learner?</summary><p>Yes. Account types are neutral. You can own one group, contribute in another and observe a Family group using the same login.</p></details><details><summary>Can observers see my subject names or resume?</summary><p>No. They receive only the aggregate progress/activity you allow.</p></details><details><summary>Why can’t a local account join a group?</summary><p>Secure cross-device membership requires a Supabase cloud identity. Personal local tracking still works offline.</p></details><details><summary>Why did an invitation stop working?</summary><p>It was used, expired after 15 minutes, or an owner/admin generated a replacement code.</p></details><details><summary>Are files allowed in messages?</summary><p>No. V1 messaging is text only to control privacy and storage cost.</p></details></div>`]
  ];
  const faq=sections.pop(),contextual=typeof window.trackerManualSections==='function'?window.trackerManualSections():[];
  sections.splice(4,0,...contextual);sections.push(faq);
  const directory=(typeof window.trackerManualDirectory==='function'?window.trackerManualDirectory():[]).map(item=>`<button type="button" onclick="scrollManual('${item.id}')">${item.label}</button>`).join('');
  return head('Help & user manual','Complete Nestlyra Focus guidance from first login to secure group collaboration',`<button class="btn ghost" onclick="loginFaqModal()">Login FAQ</button>`)+`<section class="card manual-start"><div><span class="eyebrow">QUICK START</span><h2>Personal first. Connected when you choose.</h2><p>Create one account, organize a workspace, then create or join only the groups you need.</p></div><div class="manual-steps"><button onclick="scrollManual('setup')"><b>1</b><span>Create account</span></button><button onclick="scrollManual('subjects')"><b>2</b><span>Organize work</span></button><button onclick="scrollManual('groups')"><b>3</b><span>Connect group</span></button><button onclick="scrollManual('security')"><b>4</b><span>Control privacy</span></button></div></section><label class="manual-search">⌕ <input aria-label="Search the user manual" placeholder="Search calendar, assignments, groups, projects, messages…" oninput="filterManual(this.value)"></label><div id="manualSearchStatus" class="manual-search-status" role="status"></div><div class="manual-component-directory"><strong>All components</strong><div>${directory}</div></div><div class="manual-layout"><aside class="card manual-nav"><strong>Manual contents</strong>${sections.map(([id,,title])=>`<button onclick="scrollManual('${id}')">${title}<span>→</span></button>`).join('')}</aside><div class="manual-content">${sections.map(([id,num,title,sub,body],index)=>manualSection(id,num,title,sub,body,index===0)).join('')}</div></div>`;
}
function groupLoginFaqModal(){modal(`<div class="login-faq"><span class="eyebrow">ACCOUNT & GROUP GUIDE</span><h2>One login for every Nestlyra role</h2><p>Sign in once. Your permission is assigned separately inside each group.</p><div class="login-guide-grid"><section><b>PERSONAL USE</b><h3>Your private workspace</h3><ol><li>Enter an existing email/password and choose Sign in.</li><li>For a new identity, enter details and choose Create new account.</li><li>You may also continue with Google.</li><li>A local name/PIN works offline but cannot join cloud groups.</li></ol></section><section><b>GROUP CONNECTION</b><h3>After login</h3><ol><li>Open Groups from the sidebar.</li><li>Create a group or enter a valid invitation code.</li><li>Owners choose Member, Contributor or Observer when generating the code.</li><li>The same account can have different permissions in different groups.</li></ol></section></div><div class="faq-list"><details open><summary>Do Parents need a separate login page?</summary><p>No. A parent uses a normal Nestlyra account and joins a Family group as an Observer or another permitted role.</p></details><details><summary>Can Google accounts join Groups?</summary><p>Yes. Email/password and Google cloud accounts use the same Groups system.</p></details><details><summary>Does refreshing change my account role?</summary><p>No. Roles belong to group memberships and are verified by Supabase on every request.</p></details><details><summary>What if my old account was Parent or Learner?</summary><p>The migration keeps the login and converts existing links into a Family group.</p></details><details><summary>Will refreshing restore a deleted account?</summary><p>No. Nestlyra validates the Supabase user and clears invalid cached sessions.</p></details></div><div class="modal-actions"><button class="btn primary">Close guide</button></div></div>`)}

document.addEventListener('DOMContentLoaded',()=>{
  const floating=document.querySelector('#floatingMessages');if(floating){floating.title='Group messages';floating.setAttribute('aria-label','Open group messages')}
  helpView=groupHelpView;
  window.loginFaqModal=groupLoginFaqModal;
  if(typeof MANUAL_ALIASES!=='undefined')Object.assign(MANUAL_ALIASES,{setup:'login signin signup register google password pin account group authentication',groups:'group connection invite code owner admin contributor member observer family accountability',collaboration:'shared task goal plan note progress privacy projection version conflict permission',messaging:'group message chat unread badge retention text'});
});
