/* Nestlyra Focus v37: adaptive analytics, animated sign-in, Drive resources,
   granular group sharing, profile photos, custom timer and guided onboarding. */
(() => {
  'use strict';

  const MODULE_META = {
    subjects:['Subjects','◫'],certifications:['Certifications','◇'],exams:['Exams','◎'],mocks:['Mock tests','◉'],revision:['Revision','↻'],
    assignments:['Assignments','▣'],resources:['Resources','⌘'],practice:['Practice','⚗'],projects:['Projects','◆'],tasks:['Tasks','◷'],
    calendar:['Calendar','▦'],notes:['Notes','✎'],habits:['Habits','✓'],goals:['Goals','⌁'],interviews:['Interviews','◈'],jobs:['Jobs','▤'],timer:['Study timer','◌']
  };
  const ENTITY = {
    certifications:{title:'Certification Planner',subtitle:'Readiness, milestones and exam urgency',array:'certifications',singular:'certification',fields:[['name','Certification','text','Security+'],['provider','Provider','text','CompTIA'],['examDate','Target exam date','date',''],['status','Status','select',['Planning','Learning','Revision','Booked','Completed']],['readiness','Readiness %','number','0'],['nextStep','Next milestone','textarea','Book the next practice test']]},
    exams:{title:'Exam Planner',subtitle:'Syllabus coverage, countdown and readiness gaps',array:'examPlans',singular:'exam plan',fields:[['name','Exam name','text','Final examination'],['category','Exam type','select',['School','University','Competitive','Entrance','Other']],['examDate','Exam date','date',''],['progress','Syllabus progress %','number','0'],['targetScore','Target score %','number','75'],['weakAreas','Priority chapters','textarea','']]},
    mocks:{title:'Mock Test Intelligence',subtitle:'Compare every attempt, find weak areas and improve the next score',array:'mockTests',singular:'mock attempt',fields:[['name','Test name','text','Mock test 1'],['date','Attempt date','date',''],['score','Score','number','0'],['total','Maximum score','number','100'],['duration','Duration (minutes)','number','60'],['areaBreakdown','Section scores','textarea','Networking: 8/10\nLinux: 6/10'],['notes','What happened and next action','textarea','']]},
    revision:{title:'Revision & Mistake Intelligence',subtitle:'Prioritize overdue reviews and turn low confidence into mastery',array:'revisionItems',singular:'revision item',fields:[['topic','Topic or mistake','text','Network protocols'],['kind','Type','select',['Revision','Mistake','Weak area']],['nextReview','Next review','date',''],['confidence','Confidence','select',['Low','Medium','High']],['attempts','Review attempts','number','1'],['notes','Correction and memory rule','textarea','']]},
    assignments:{title:'Assignment Performance',subtitle:'Deadlines, submission health and grade patterns',array:'assignments',singular:'assignment',fields:[['title','Assignment','text','Complete chapter exercise'],['subject','Subject or area','text','Mathematics'],['dueDate','Due date','date',''],['priority','Priority','select',['Low','Medium','High']],['status','Status','select',['Not started','In progress','Submitted','Graded']],['grade','Grade or result','text',''],['feedback','Teacher feedback / correction','textarea','']]},
    resources:{title:'Resource Library',subtitle:'Curate useful links · Google Drive PDF storage is coming soon',array:'resources',singular:'resource',fields:[['title','Resource title','text','Official study guide'],['type','Resource type','select',['Book','Course','Video','Article','Tool','Website','Other']],['url','Link','url','https://'],['status','Status','select',['Saved','In use','Completed']],['rating','Usefulness (1–5)','number','0'],['notes','Why it is useful','textarea','']]},
    practice:{title:'Practice Intelligence',subtitle:'Measure score trends across labs, quizzes and past papers',array:'practiceItems',singular:'practice entry',fields:[['title','Practice activity','text','Timed practice set'],['category','Type','select',['Lab','Problem set','Past paper','Quiz','Exercise','Other']],['date','Practice date','date',''],['score','Score','number','0'],['total','Maximum score','number','100'],['duration','Duration (minutes)','number','30'],['notes','Mistakes and next action','textarea','']]},
    projects:{title:'Project Delivery',subtitle:'See momentum, blockers and upcoming milestones',array:'projects',singular:'project',fields:[['title','Project name','text','Portfolio project'],['area','Area','text','Cybersecurity'],['targetDate','Target date','date',''],['progress','Progress %','number','0'],['status','Status','select',['Planning','Active','Blocked','Completed']],['nextMilestone','Next milestone','text',''],['notes','Milestones, blockers and next steps','textarea','']]},
    habits:{title:'Habit Consistency',subtitle:'Build repeatable routines and monitor weekly adherence',array:'habits',singular:'habit',fields:[['name','Habit name','text','Study for 30 minutes'],['frequency','Frequency','select',['Daily','Weekdays','Weekly']],['target','Weekly target','number','5']]},
    goals:{title:'Goal Forecast',subtitle:'Track outcomes, pace and deadline risk',array:'goals',singular:'goal',fields:[['title','Goal','text','Finish the complete syllabus'],['targetDate','Target date','date',''],['progress','Progress %','number','0'],['priority','Priority','select',['Low','Medium','High']],['notes','Success criteria and next milestone','textarea','']]},
    interviews:{title:'Interview Readiness',subtitle:'Track stages, preparation coverage and next actions',array:'interviewPrep',singular:'interview plan',fields:[['company','Company','text','Example company'],['role','Role','text','Security Analyst'],['round','Round','select',['Preparation','Recruiter','Technical','Managerial','Final']],['date','Interview date','date',''],['status','Status','select',['Preparing','Scheduled','Completed','Passed','Closed']],['readiness','Readiness %','number','0'],['topics','Questions, topics and follow-up','textarea','']]}
  };
  const chartBag = {};
  const pctOf = item => Math.max(0,Math.min(100,Math.round(Number(item.score||0)/Math.max(1,Number(item.total||100))*100)));
  const clamp = n => Math.max(0,Math.min(100,Math.round(Number(n)||0)));
  const daysUntil = value => value ? Math.ceil((new Date(`${value}T12:00:00`)-new Date())/86400000) : null;
  const avg = values => values.length ? Math.round(values.reduce((a,b)=>a+b,0)/values.length) : 0;
  const activeModules = () => Object.keys(MODULE_META).filter(id => typeof trackerModuleEnabled!=='function'||trackerModuleEnabled(id));

  function moduleMetric(id) {
    let items=[],complete=0,total=0,progress=0,detail='No records yet';
    if(id==='subjects'){items=allTopics();total=items.length;complete=items.filter(x=>x.status==='completed').length;progress=total?complete/total*100:0;detail=`${complete}/${total} topics`}
    else if(id==='tasks'){items=state.tasks||[];total=items.length;complete=items.filter(x=>x.status==='completed').length;progress=total?complete/total*100:0;detail=`${items.filter(x=>x.due&&x.due<today()&&x.status!=='completed').length} overdue`}
    else if(id==='jobs'){items=state.jobApplications||[];total=items.length;complete=items.filter(x=>['Selected','Offer','Rejected','Withdrawn'].includes(x.status)).length;progress=total?complete/total*100:0;detail=`${items.filter(x=>x.status==='Interview').length} interviews`}
    else if(id==='notes'){items=state.notes||[];total=items.length;complete=items.filter(x=>x.content?.trim()).length;progress=total?complete/total*100:0;detail=`${total} notes`}
    else if(id==='calendar'){items=[...(state.events||[]),...(state.tasks||[]).filter(x=>x.due)];total=items.length;complete=items.filter(x=>x.status==='completed').length;progress=total?Math.max(10,complete/total*100):0;detail=`${items.filter(x=>(x.date||x.due)>=today()).length} upcoming`}
    else if(id==='timer'){const mins=(state.activity||[]).filter(x=>x.date>=dateOffset(-6)).reduce((s,x)=>s+Number(x.minutes||0),0);total=300;complete=Math.min(total,mins);progress=complete/total*100;detail=`${mins} min / 7 days`}
    else {const def=ENTITY[id];items=def?state[def.array]||[]:[];total=items.length;const scores=items.map(x=>entityProgress(id,x));complete=scores.filter(x=>x>=100).length;progress=avg(scores);detail=total?`${total} record${total===1?'':'s'}`:'No records yet'}
    return {id,label:MODULE_META[id]?.[0]||id,icon:MODULE_META[id]?.[1]||'•',progress:clamp(progress),complete,total,detail};
  }
  function entityProgress(kind,item){
    if(['mocks','practice'].includes(kind))return pctOf(item);
    if(['exams','projects','goals'].includes(kind))return clamp(item.progress);
    if(kind==='certifications')return clamp(item.readiness||({Planning:10,Learning:45,Revision:75,Booked:90,Completed:100}[item.status]||0));
    if(kind==='revision')return ({Low:25,Medium:60,High:100}[item.confidence]||0);
    if(kind==='assignments')return ({'Not started':0,'In progress':45,Submitted:85,Graded:100}[item.status]||0);
    if(kind==='resources')return ({Saved:20,'In use':60,Completed:100}[item.status]||0);
    if(kind==='habits'){const week=new Set(Array.from({length:7},(_,i)=>dateOffset(-i)));return clamp((item.completedDates||[]).filter(x=>week.has(x)).length/Math.max(1,Number(item.target||1))*100)}
    if(kind==='interviews')return clamp(item.readiness||({Preparing:25,Scheduled:55,Completed:75,Passed:100,Closed:100}[item.status]||0));
    return 0;
  }
  function dateOffset(delta){const d=new Date();d.setDate(d.getDate()+delta);return d.toISOString().slice(0,10)}
  function h(value=''){return escapeHtml(String(value))}

  function dashboardContext(metrics,topics,weekMinutes){
    const preset=state.moduleConfig?.preset||'custom',subjectRows=(state.subjects||[]).map(item=>({label:item.name,value:pct(item)}));
    const completeTopics=topics.filter(x=>x.status==='completed').length,dueTasks=(state.tasks||[]).filter(x=>x.status!=='completed'&&x.due===today()).length;
    const generic={key:'custom',eyebrow:'CUSTOM WORKSPACE',subtitle:'Every enabled section uses its own readiness criteria',chartTitle:'Enabled-module readiness',rows:metrics.map(x=>({label:x.label,value:x.progress})),stats:[['◎','Workspace readiness',`${avg(metrics.filter(x=>x.total||x.progress).map(x=>x.progress))}%`],['✓','Topics complete',completeTopics],['◷','Due today',dueTasks],['⌁','Seven-day focus',`${Math.round(weekMinutes/6)/10}h`]]};
    if(preset==='school')return {...generic,key:'student',eyebrow:'STUDENT COURSE VIEW',subtitle:'Course depth, topic completion, deadlines and study consistency',chartTitle:'Course progress by subject',rows:subjectRows,stats:[['◫','Courses',(state.subjects||[]).length],['✓','Topics complete',`${completeTopics}/${topics.length}`],['▣','Work due today',dueTasks+(state.assignments||[]).filter(x=>x.dueDate===today()&&!['Submitted','Graded'].includes(x.status)).length],['⌁','Seven-day study',`${Math.round(weekMinutes/6)/10}h`]]};
    if(preset==='certification'){
      const certs=state.certifications||[],mockScores=(state.mockTests||[]).map(pctOf),nearest=certs.map(x=>daysUntil(x.examDate)).filter(x=>x!==null&&x>=0).sort((a,b)=>a-b)[0];
      return {...generic,key:'certification',eyebrow:'CERTIFICATION READINESS',subtitle:'Evidence-based readiness, exam urgency, practice and revision',chartTitle:'Certification readiness',rows:certs.map(x=>({label:x.name||'Certification',value:entityProgress('certifications',x)})),stats:[['◇','Average readiness',`${avg(certs.map(x=>entityProgress('certifications',x)))}%`],['◉','Mock average',mockScores.length?`${avg(mockScores)}%`:'—'],['↻','Revision due',(state.revisionItems||[]).filter(x=>x.nextReview&&x.nextReview<=today()&&x.confidence!=='High').length],['◷','Nearest exam',nearest===undefined?'Not set':`${nearest}d`]]};
    }
    if(preset==='competitive'){
      const exams=state.examPlans||[],mocks=state.mockTests||[],latest=mocks.length?pctOf([...mocks].sort((a,b)=>String(a.date).localeCompare(String(b.date))).at(-1)):null;
      return {...generic,key:'exam',eyebrow:'COMPETITIVE EXAM CONTROL',subtitle:'Syllabus coverage, mock trajectory, weak areas and revision load',chartTitle:'Exam and mock readiness',rows:[...exams.map(x=>({label:x.name||'Exam syllabus',value:clamp(x.progress)})),...mocks.slice(-4).map((x,i)=>({label:x.name||`Mock ${i+1}`,value:pctOf(x)}))],stats:[['◎','Syllabus coverage',`${avg(exams.map(x=>clamp(x.progress)))}%`],['◉','Latest mock',latest===null?'—':`${latest}%`],['↻','Low-confidence areas',(state.revisionItems||[]).filter(x=>x.confidence==='Low').length],['⚗','Practice attempts',(state.practiceItems||[]).length]]};
    }
    if(preset==='job'){
      const jobs=state.jobApplications||[],interviews=state.interviewPrep||[],followups=jobs.filter(x=>x.followUpDate&&x.followUpDate<=today()&&!['Rejected','Withdrawn','Selected','Offer'].includes(x.status)).length;
      const stages=['Wishlist','Applied','Screening','Interview','Offer'].map(stage=>({label:stage,value:jobs.filter(x=>String(x.status).toLowerCase().includes(stage.toLowerCase())).length*20}));
      return {...generic,key:'career',eyebrow:'CAREER PIPELINE',subtitle:'Application movement, interview readiness and follow-up discipline',chartTitle:'Application pipeline activity',rows:stages,stats:[['▤','Applications',jobs.length],['◈','Interview readiness',`${avg(interviews.map(x=>entityProgress('interviews',x)))}%`],['◷','Follow-ups due',followups],['◆','Portfolio projects',(state.projects||[]).filter(x=>x.status==='Active').length]]};
    }
    if(preset==='daily')return {...generic,key:'productivity',eyebrow:'DAILY EXECUTION',subtitle:'Task completion, habit consistency, goals and protected focus time',chartTitle:'Routine and goal health',rows:metrics.filter(x=>['tasks','habits','goals','timer','projects'].includes(x.id)).map(x=>({label:x.label,value:x.progress})),stats:[['◷','Tasks remaining',(state.tasks||[]).filter(x=>x.status!=='completed').length],['✓','Habit consistency',`${moduleMetric('habits').progress}%`],['⌁','Goal pace',`${moduleMetric('goals').progress}%`],['◌','Seven-day focus',`${Math.round(weekMinutes/6)/10}h`]]};
    return generic;
  }

  function dashboardMarkup(){
    const metrics=activeModules().map(moduleMetric),withData=metrics.filter(x=>x.total||x.progress),overallScore=avg(withData.map(x=>x.progress));
    const topics=allTopics(),completed=topics.filter(x=>x.status==='completed').length;
    const due=(state.tasks||[]).filter(x=>x.status!=='completed'&&x.due===today()).length;
    const weekMinutes=(state.activity||[]).filter(x=>x.date>=dateOffset(-6)).reduce((s,x)=>s+Number(x.minutes||0),0);
    const focus=metrics.slice().sort((a,b)=>a.progress-b.progress).find(x=>x.total)||metrics[0];
    const plan=[...(state.tasks||[]).filter(x=>x.status!=='completed'&&x.due===today()).map(x=>x.title),...topics.filter(x=>x.status!=='completed'&&x.due===today()).map(x=>x.name)].slice(0,3);
    const context=dashboardContext(metrics,topics,weekMinutes);window.nestlyraDashboardContext=context;setTimeout(drawDashboardCharts,0);
    return head(`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${h((state.profile?.name||'Learner').split(' ')[0])}`,context.subtitle)+
      `<div class="dashboard-role-label ${context.key}"><span>${context.eyebrow}</span><small>Dashboard criteria automatically follow this workspace preset</small></div><div class="grid stats v37-dashboard-stats">${context.stats.map(([icon,label,value])=>`<div class="stat"><div class="stat-icon">${icon}</div><div><small>${h(label)}</small><strong>${h(value)}</strong></div></div>`).join('')}</div>`+
      `<div class="v37-dashboard-grid"><section class="card v37-chart-card"><div class="card-title"><h3>${h(context.chartTitle)}</h3><span>${context.rows.length} tracked ${context.rows.length===1?'area':'areas'}</span></div><div class="v37-chart-wrap"><canvas id="v37ModuleChart"></canvas></div></section>`+
      `<section class="card v37-trend-card"><div class="card-title"><h3>Focus trend</h3><span>Last 7 days</span></div><div class="v37-chart-wrap small"><canvas id="v37FocusChart"></canvas></div><div class="v37-focus-callout"><span>${focus?.icon||'◎'}</span><div><small>Recommended focus</small><strong>${h(focus?.label||'Create your first record')}</strong><p>${focus?.total?`${focus.progress}% ready · ${h(focus.detail)}`:'Add data to unlock recommendations.'}</p></div></div></section>`+
      `<section class="card v37-today-card"><div class="card-title"><h3>Today</h3>${typeof trackerModuleEnabled==='function'&&trackerModuleEnabled('calendar')?'<button onclick="setView(\'calendar\')">Calendar →</button>':''}</div>${plan.length?plan.map(x=>`<div class="v37-plan-row"><span>✓</span><b>${h(x)}</b></div>`).join(''):'<div class="empty compact-empty">Nothing urgent. Use Quick add or Calendar to plan.</div>'}</section></div>`;
  }
  function drawDashboardCharts(){
    if(!window.Chart)return;Object.values(chartBag).forEach(chart=>chart?.destroy?.());
    const metrics=activeModules().map(moduleMetric).filter(x=>x.total||x.progress).slice(0,12),context=window.nestlyraDashboardContext||dashboardContext(metrics,allTopics(),0),rows=context.rows.length?context.rows:metrics.map(x=>({label:x.label,value:x.progress}));
    const css=getComputedStyle(document.body),accent=css.getPropertyValue('--accent').trim()||'#4c5fd5',muted=css.getPropertyValue('--muted').trim()||'#5b6478',line=css.getPropertyValue('--line').trim()||'#e4e9f2';
    const moduleCanvas=document.querySelector('#v37ModuleChart');if(moduleCanvas)chartBag.modules=new Chart(moduleCanvas,{type:'bar',data:{labels:rows.map(x=>x.label),datasets:[{data:rows.map(x=>x.value),backgroundColor:rows.map((_,i)=>i%2?accent:'#20b8a6'),borderRadius:6,maxBarThickness:18}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:'y',animation:{duration:500},scales:{x:{beginAtZero:true,max:Math.max(100,...rows.map(x=>Number(x.value)||0)),ticks:{color:muted,font:{size:9}},grid:{color:line}},y:{ticks:{color:muted,font:{size:9}},grid:{display:false}}},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw}${context.key==='career'?' pipeline points':'% ready'}`}}}}});
    const days=Array.from({length:7},(_,i)=>dateOffset(i-6)),minutes=days.map(day=>(state.activity||[]).filter(x=>x.date===day).reduce((s,x)=>s+Number(x.minutes||0),0));
    const focusCanvas=document.querySelector('#v37FocusChart');if(focusCanvas)chartBag.focus=new Chart(focusCanvas,{type:'line',data:{labels:days.map(x=>new Date(`${x}T12:00`).toLocaleDateString(undefined,{weekday:'short'})),datasets:[{data:minutes,borderColor:accent,backgroundColor:`${accent}22`,fill:true,tension:.35,pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{color:muted,font:{size:8}},grid:{color:line}},x:{ticks:{color:muted,font:{size:8}},grid:{display:false}}},plugins:{legend:{display:false}}}});
  }

  function parseAreas(text=''){
    return text.split(/\n|,/).map(part=>{const match=part.trim().match(/^(.+?):\s*(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)$/);return match?{name:match[1].trim(),score:Number(match[2]),total:Number(match[3]),pct:Math.round(Number(match[2])/Math.max(1,Number(match[3]))*100)}:null}).filter(Boolean);
  }
  function entityAnalysis(kind,items){
    const scores=items.map(x=>entityProgress(kind,x)),average=avg(scores),sorted=[...items].sort((a,b)=>String(a.date||a.examDate||a.targetDate||a.dueDate||a.nextReview||'').localeCompare(String(b.date||b.examDate||b.targetDate||b.dueDate||b.nextReview||'')));
    let cards=[['Average readiness',`${average}%`],['Completed',scores.filter(x=>x>=100).length],['Records',items.length]],suggestion='Add records consistently to unlock a reliable recommendation.',areas=[];
    if(kind==='mocks'){
      const attempts=sorted.map(pctOf),delta=attempts.length>1?attempts.at(-1)-attempts.at(-2):0;areas=items.flatMap(x=>parseAreas(x.areaBreakdown));const grouped={};areas.forEach(x=>{(grouped[x.name]??=[]).push(x.pct)});areas=Object.entries(grouped).map(([name,v])=>({name,pct:avg(v)})).sort((a,b)=>a.pct-b.pct);
      cards=[['Current',attempts.length?`${attempts.at(-1)}%`:'—'],['Change',attempts.length>1?`${delta>=0?'+':''}${delta}%`:'Need 2 attempts'],['Best',attempts.length?`${Math.max(...attempts)}%`:'—']];
      suggestion=areas.length?`Revise ${areas[0].name} first (${areas[0].pct}%). ${delta>0?'Your latest score improved—repeat the same preparation cycle.':delta<0?'Your latest score fell; review timing and recurring errors before retesting.':'Use the mistake log before the next attempt.'}`:'Add section scores such as “Networking: 8/10” to identify strong and weak areas.';
    } else if(kind==='revision'){
      const overdue=items.filter(x=>x.nextReview&&x.nextReview<today()&&x.confidence!=='High').length,low=items.filter(x=>x.confidence==='Low').length;cards=[['Overdue reviews',overdue],['Low confidence',low],['Mastered',items.filter(x=>x.confidence==='High').length]];suggestion=overdue?`Review ${overdue} overdue item${overdue===1?'':'s'} first, beginning with Low confidence mistakes.`:low?'Schedule the Low confidence items with spaced review dates.':'Keep High-confidence items on a lighter maintenance cycle.';
    } else if(kind==='assignments'){
      const overdue=items.filter(x=>x.dueDate&&x.dueDate<today()&&!['Submitted','Graded'].includes(x.status)).length;cards=[['On track',items.length-overdue],['Overdue',overdue],['Graded',items.filter(x=>x.status==='Graded').length]];suggestion=overdue?'Move overdue high-priority work into Today’s plan.':'Record feedback after grading so repeated mistakes become revision items.';
    } else if(kind==='projects'){
      const blocked=items.filter(x=>x.status==='Blocked').length;cards=[['Average progress',`${average}%`],['Blocked',blocked],['Active',items.filter(x=>x.status==='Active').length]];suggestion=blocked?'Resolve the oldest blocked project before starting another milestone.':'Keep one explicit next milestone on every active project.';
    } else if(kind==='resources'){
      cards=[['In use',items.filter(x=>x.status==='In use').length],['Completed',items.filter(x=>x.status==='Completed').length],['Drive PDFs','Soon']];suggestion=items.filter(x=>x.status==='Saved').length?'Move only the most useful saved resource into “In use” to reduce overload.':'Add a useful course, book, article or website link.';
    } else if(kind==='habits'){
      cards=[['Weekly consistency',`${average}%`],['Done today',items.filter(x=>(x.completedDates||[]).includes(today())).length],['Habits',items.length]];suggestion=average<60?'Reduce the weekly target or attach the habit to a fixed time.':'Consistency is healthy—protect the routine before adding another habit.';
    } else if(kind==='goals'){
      const overdue=items.filter(x=>x.targetDate&&x.targetDate<today()&&Number(x.progress)<100).length;cards=[['Average progress',`${average}%`],['At risk',overdue],['Complete',items.filter(x=>Number(x.progress)>=100).length]];suggestion=overdue?'Re-scope the overdue goal into one measurable next milestone.':'Update progress weekly and make each goal’s next step visible in Tasks.';
    } else if(kind==='interviews'){
      cards=[['Readiness',`${average}%`],['Upcoming',items.filter(x=>x.date>=today()&&!['Closed','Passed'].includes(x.status)).length],['Passed',items.filter(x=>x.status==='Passed').length]];suggestion=items.some(x=>x.date>=today()&&entityProgress(kind,x)<70)?'Prioritize the nearest interview below 70% readiness and rehearse its listed topics.':'Record questions after every round to improve the next interview.';
    } else if(kind==='practice'){
      const attempts=sorted.map(pctOf),delta=attempts.length>1?attempts.at(-1)-attempts.at(-2):0;cards=[['Average score',`${avg(attempts)}%`],['Latest change',attempts.length>1?`${delta>=0?'+':''}${delta}%`:'Need 2 entries'],['Minutes',items.reduce((s,x)=>s+Number(x.duration||0),0)]];suggestion=delta<0?'Repeat the weakest practice category untimed, then retest under time pressure.':'Keep practice conditions consistent so score comparisons remain meaningful.';
    } else {
      const nearest=items.map(x=>daysUntil(x.examDate||x.targetDate)).filter(x=>x!==null&&x>=0).sort((a,b)=>a-b)[0];cards=[['Average readiness',`${average}%`],['Completed',scores.filter(x=>x>=100).length],['Next deadline',nearest===undefined?'None':`${nearest}d`]];suggestion=nearest!==undefined&&nearest<14&&average<70?'The next deadline is close; reduce new material and prioritize weak areas.':'Keep readiness and the next milestone updated for a useful forecast.';
    }
    return {cards,suggestion,scores,sorted,areas};
  }
  function entityLabel(def,item){return item.name||item.topic||item.title||item.company||def.singular}
  function entityMeta(kind,item){
    const map={certifications:[item.provider,item.examDate,item.status],exams:[item.category,item.examDate,`${clamp(item.progress)}% syllabus`],mocks:[item.date,`${item.score||0}/${item.total||100}`,item.duration&&`${item.duration} min`],revision:[item.kind,item.confidence,item.nextReview],assignments:[item.subject,item.dueDate,item.status,item.grade],resources:[item.type,item.status,item.driveFileId?'Google Drive':''],practice:[item.category,item.date,`${item.score||0}/${item.total||100}`],projects:[item.area,item.targetDate,item.status],habits:[item.frequency,`${(item.completedDates||[]).length} check-ins`],goals:[item.targetDate,`${clamp(item.progress)}%`],interviews:[item.role,item.round,item.date,item.status]};
    return (map[kind]||[]).filter(Boolean).join(' · ');
  }
  const ENTITY_VISUAL={
    certifications:{icon:'◇',lens:'Credential readiness',chart:'Readiness radar',criteria:['Exam date','Evidence & milestones','Readiness score']},
    exams:{icon:'◎',lens:'Syllabus command',chart:'Coverage spectrum',criteria:['Coverage','Target score','Weak chapters']},
    mocks:{icon:'◉',lens:'Attempt intelligence',chart:'Score trajectory',criteria:['Attempt change','Section weakness','Time pressure']},
    revision:{icon:'↻',lens:'Recall strength',chart:'Confidence backlog',criteria:['Review interval','Confidence','Repeated mistakes']},
    assignments:{icon:'▣',lens:'Submission health',chart:'Status distribution',criteria:['Deadline risk','Submission stage','Feedback loop']},
    resources:{icon:'⌘',lens:'Resource value',chart:'Usefulness ranking',criteria:['Active use','Rating','Completion']},
    practice:{icon:'⚗',lens:'Deliberate practice',chart:'Accuracy curve',criteria:['Accuracy','Duration','Practice type']},
    projects:{icon:'◆',lens:'Delivery momentum',chart:'Milestone progress',criteria:['Progress','Blockers','Next milestone']},
    habits:{icon:'✓',lens:'Consistency system',chart:'Weekly adherence',criteria:['Today check-in','Weekly target','Streak stability']},
    goals:{icon:'⌁',lens:'Outcome forecast',chart:'Goal pace',criteria:['Progress','Deadline risk','Success criteria']},
    interviews:{icon:'◈',lens:'Interview pipeline',chart:'Round readiness',criteria:['Current round','Readiness','Question evidence']}
  };
  function entityBlueprint(kind){const visual=ENTITY_VISUAL[kind];return `<div class="entity-blueprint"><span>${visual.icon}</span><div><small>${h(visual.lens)}</small><strong>${h(visual.chart)}</strong></div>${visual.criteria.map(item=>`<i>${h(item)}</i>`).join('')}</div>`}
  function richEntityView(kind){
    const def=ENTITY[kind],items=state[def.array]||[],analysis=entityAnalysis(kind,items),visual=ENTITY_VISUAL[kind],actions=`<button class="btn primary" onclick="trackerItemModal('${kind}')">+ Add ${h(def.singular)}</button>${kind==='resources'?'<button class="btn ghost" type="button" disabled title="Google Drive PDF storage is coming soon">☁ Drive PDF · Coming soon</button>':''}`;
    setTimeout(()=>drawEntityCharts(kind,analysis),0);
    return `<div class="v37-kind-${kind}">`+head(def.title,def.subtitle,`<div class="page-actions">${actions}</div>`)+entityBlueprint(kind)+`<div class="grid stats v37-entity-stats">${analysis.cards.map(([label,value],i)=>`<div class="stat"><div class="stat-icon">${[visual.icon,'↗','◇'][i]}</div><div><small>${h(label)}</small><strong>${h(value)}</strong></div></div>`).join('')}<div class="stat insight-stat"><div class="stat-icon">✦</div><div><small>Insight engine</small><strong>${analysis.scores.length?'Live':'Waiting'}</strong></div></div></div>`+
      `<div class="v37-entity-grid"><section class="card v37-insight-card"><div class="card-title"><h3>${h(visual.chart)}</h3><span>${h(visual.lens)}</span></div><div class="v37-entity-chart"><canvas id="v37EntityChart"></canvas></div><p class="v37-suggestion"><span>✦</span>${h(analysis.suggestion)}</p>${kind==='mocks'&&analysis.areas.length?`<div class="v37-area-pills">${analysis.areas.slice(0,5).map(x=>`<span class="${x.pct<60?'weak':x.pct>=80?'strong':''}">${h(x.name)} <b>${x.pct}%</b></span>`).join('')}</div>`:''}</section>`+
      `<section class="card v37-record-card"><div class="card-title"><h3>${h(visual.lens)} records</h3><span>${items.length}</span></div><div class="entity-list">${items.length?items.map(item=>`<article class="entity-row"><button class="entity-main" onclick="trackerItemModal('${kind}','${item.id}')"><span class="entity-icon">${MODULE_META[kind]?.[1]||'◇'}</span><span><strong>${h(entityLabel(def,item))}</strong><small>${h(entityMeta(kind,item)||'No details yet')}</small><i><b style="width:${entityProgress(kind,item)}%"></b></i></span></button>${kind==='resources'&&item.url?`<a class="mini-btn" href="${h(item.url)}" target="_blank" rel="noopener" title="Open resource">↗</a>`:''}${kind==='habits'?`<button class="habit-check ${(item.completedDates||[]).includes(today())?'done':''}" onclick="trackerToggleHabit('${item.id}')">${(item.completedDates||[]).includes(today())?'✓ Done':'Mark today'}</button>`:''}<button class="mini-btn" onclick="trackerDeleteItem('${kind}','${item.id}')">×</button></article>`).join(''):`<div class="empty compact-empty"><h3>Add the first ${h(def.singular)}</h3><p>Nestlyra will calculate ${h(visual.lens.toLowerCase())} insights as your history grows.</p></div>`}</div></section></div></div>`;
  }
  function drawEntityCharts(kind,analysis){
    const canvas=document.querySelector('#v37EntityChart');if(!canvas||!window.Chart)return;chartBag.entity?.destroy?.();const css=getComputedStyle(document.body),accent=css.getPropertyValue('--accent').trim()||'#4c5fd5',muted=css.getPropertyValue('--muted').trim()||'#5b6478',line=css.getPropertyValue('--line').trim()||'#e4e9f2';
    const labels=analysis.sorted.map((item,index)=>item.date||item.examDate||item.targetDate||item.dueDate||item.nextReview||`#${index+1}`),values=analysis.sorted.map(item=>entityProgress(kind,item));
    const palette=[accent,'#20b8a6','#f5a623','#e35d78','#7d63da','#4b91e2'],axis={ticks:{color:muted,font:{size:8}},grid:{color:line}},baseOptions={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}};
    let type='line',data={labels,datasets:[{label:'Progress %',data:values,borderColor:accent,backgroundColor:`${accent}2d`,fill:true,tension:.32,borderWidth:2,pointRadius:3,borderRadius:5}]},options={...baseOptions,scales:{y:{beginAtZero:true,max:100,...axis},x:{...axis,grid:{display:false}}}};
    if(kind==='certifications'||kind==='interviews'){
      type='radar';
      data={labels:analysis.sorted.map((item,index)=>entityLabel(ENTITY[kind],item)||`#${index+1}`),datasets:[{data:values,borderColor:accent,backgroundColor:`${accent}2d`,pointBackgroundColor:accent}]};
      options={...baseOptions,scales:{r:{beginAtZero:true,max:100,ticks:{display:false},grid:{color:line},angleLines:{color:line},pointLabels:{color:muted,font:{size:8}}}}};
    }else if(kind==='exams'){
      type='polarArea';
      data={labels:analysis.sorted.map((item,index)=>item.name||`Exam ${index+1}`),datasets:[{data:values,backgroundColor:values.map((_,i)=>`${palette[i%palette.length]}99`),borderWidth:0}]};
      options={...baseOptions,scales:{r:{beginAtZero:true,max:100,ticks:{display:false},grid:{color:line}}}};
    }else if(kind==='assignments'){
      const statuses=['Not started','In progress','Submitted','Graded'];type='doughnut';
      data={labels:statuses,datasets:[{data:statuses.map(status=>analysis.sorted.filter(x=>x.status===status).length),backgroundColor:palette.slice(0,4),borderWidth:0}]};
      options={...baseOptions,cutout:'62%',plugins:{legend:{display:true,position:'bottom',labels:{color:muted,boxWidth:8,font:{size:8}}}}};
    }else if(kind==='resources'){
      type='bar';
      data={labels:analysis.sorted.map((item,index)=>item.title||`Resource ${index+1}`),datasets:[{data:analysis.sorted.map(x=>clamp(Number(x.rating||0)*20)),backgroundColor:palette,borderRadius:6}]};
      options={...baseOptions,indexAxis:'y',scales:{x:{beginAtZero:true,max:100,...axis},y:{...axis,grid:{display:false}}}};
    }else if(['revision','projects','habits','goals'].includes(kind)){
      type='bar';options={...baseOptions,indexAxis:kind==='revision'?'y':'x',scales:{y:{beginAtZero:true,max:kind==='revision'?undefined:100,...axis},x:{beginAtZero:true,max:kind==='revision'?100:undefined,...axis,grid:{color:line}}}};data.datasets[0].fill=false;data.datasets[0].backgroundColor=values.map((_,i)=>palette[i%palette.length]);
    }else if(kind==='practice'){
      data.datasets[0].tension=0;data.datasets[0].borderColor='#20b8a6';data.datasets[0].backgroundColor='#20b8a622';
    }
    chartBag.entity=new Chart(canvas,{type,data,options});
  }

  function fieldMarkup([key,label,type,option],item){const value=item?.[key]??'';if(type==='select')return `<label>${h(label)}<select id="v37Field_${key}">${option.map(choice=>`<option ${value===choice?'selected':''}>${h(choice)}</option>`).join('')}</select></label>`;if(type==='textarea')return `<label class="full">${h(label)}<textarea id="v37Field_${key}" rows="4" placeholder="${h(option||'')}">${h(value)}</textarea></label>`;return `<label>${h(label)}<input id="v37Field_${key}" type="${type}" value="${h(value)}" placeholder="${h(option||'')}"></label>`}
  window.trackerItemModal=(kind,id='')=>{const def=ENTITY[kind];if(!def)return;const item=(state[def.array]||[]).find(x=>x.id===id);modal(`<h2>${item?'Edit':'Add'} ${h(def.singular)}</h2><p class="task-meta">The details below power this section’s comparisons, graphs and recommendations.</p><div class="form-grid">${def.fields.map(field=>fieldMarkup(field,item)).join('')}</div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="trackerSaveItemV37('${kind}','${id}')">Save</button></div>`)};
  window.trackerSaveItemV37=(kind,id='')=>{const def=ENTITY[kind],items=state[def.array]||[],existing=items.find(x=>x.id===id),data={};def.fields.forEach(([key,,type])=>{const input=document.querySelector(`#v37Field_${key}`);data[key]=type==='number'?Number(input?.value||0):(input?.value||'').trim()});if(!entityLabel(def,data)?.trim())return toast(`Enter a ${def.singular} name`);if(existing)Object.assign(existing,data);else items.unshift({id:uid(),createdAt:new Date().toISOString(),...data,...(kind==='habits'?{completedDates:[]}:{})});state[def.array]=items;save();closeModal();render();toast(existing?'Record updated':'Record added')};

  function customTimerView(){const mins=String(Math.floor(timerSeconds/60)).padStart(2,'0'),secs=String(timerSeconds%60).padStart(2,'0');return head('Study timer','Use a preset or any custom duration from 1 to 360 minutes')+`<section class="card timer-shell v37-timer"><span class="eyebrow">FOCUS SESSION</span><div id="timerDisplay" class="timer-display">${mins}:${secs}</div><div class="timer-presets"><button class="btn ghost" onclick="setTimer(25)">25 min</button><button class="btn ghost" onclick="setTimer(45)">45 min</button><button class="btn ghost" onclick="setTimer(60)">60 min</button></div><div class="custom-timer-control"><label>Custom minutes<input id="customTimerMinutes" type="number" min="1" max="360" value="${Math.round(timerInitial/60)}"></label><button class="btn ghost" onclick="setCustomTimer()">Set custom time</button></div><p id="timerStatus" class="timer-status">${timerHandle?'Session running':'Ready when you are'}</p><div class="timer-actions"><button class="btn primary" onclick="startTimer()">▶ Start</button><button class="btn ghost" onclick="pauseTimer()">Pause</button><button class="btn danger" onclick="resetTimer()">Reset</button></div></section>`}
  window.setCustomTimer=()=>{const input=document.querySelector('#customTimerMinutes'),minutes=Math.round(Number(input?.value||0));if(minutes<1||minutes>360)return toast('Choose between 1 and 360 minutes');setTimer(minutes);render()};

  function updateAvatar(){const button=document.querySelector('#avatar');if(!button)return;if(!button.querySelector('#avatarImage'))button.innerHTML='<img id="avatarImage" alt="" class="hidden"><span id="avatarInitial">P</span>';const image=button.querySelector('#avatarImage'),initial=button.querySelector('#avatarInitial'),photo=state.profile?.photo||'';image.src=photo;image.classList.toggle('hidden',!photo);initial.classList.toggle('hidden',Boolean(photo));initial.textContent=(state.profile?.name||'P')[0].toUpperCase()}
  function compressProfileImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const size=256,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(canvas.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
  window.profileModal=()=>modal(`<h2>Profile & photo</h2><div class="profile-photo-editor"><img id="profilePhotoPreview" src="${h(state.profile?.photo||'nestlyra-logo.png')}" alt="Profile preview"><label class="btn ghost">Choose photo<input id="profilePhotoFile" type="file" accept="image/jpeg,image/png,image/webp" onchange="previewProfilePhoto(event)"></label><button type="button" class="btn ghost" onclick="removeProfilePhoto()">Remove photo</button></div><div class="form-grid"><label class="full">Display name<input id="fProfileName" value="${h(state.profile?.name||'')}"></label><label class="full">New local PIN / password<input id="fProfilePin" type="password" minlength="4" placeholder="Leave blank to keep current"></label></div><p class="task-meta">Your photo is optimized to 256 × 256 pixels and used only in the upper-right profile button. Login-page images are no longer user-customizable.</p><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveProfileV37()">Save profile</button></div>`);
  let pendingPhoto=null;
  window.previewProfilePhoto=async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024)return toast('Choose an image smaller than 5 MB');try{pendingPhoto=await compressProfileImage(file);document.querySelector('#profilePhotoPreview').src=pendingPhoto}catch{toast('This image could not be opened')}};
  window.removeProfilePhoto=()=>{pendingPhoto='';const preview=document.querySelector('#profilePhotoPreview');if(preview)preview.src='nestlyra-logo.png'};
  window.saveProfileV37=async()=>{state.profile=state.profile||{};state.profile.name=document.querySelector('#fProfileName')?.value.trim()||state.profile.name||'Nestlyra user';if(pendingPhoto!==null)state.profile.photo=pendingPhoto;const password=document.querySelector('#fProfilePin')?.value;if(password&&cloudUser&&sb){const {error}=await sb.auth.updateUser({password,data:{full_name:state.profile.name}});if(error)return toast(error.message)}else if(password)state.profile.pin=password;pendingPhoto=null;save();updateAvatar();closeModal();render();toast('Profile updated')};

  function appearanceMarkup(){const s={...state.settings},themes=[['nestlyra','Nestlyra Calm','#4C5FD5'],['auto','Automatic','#7181EA'],['dark','Midnight','#111d2e'],['ocean','Ocean','#1b9cff'],['cyber','Cyber','#ff3e9d'],['matrix','Matrix','#3cdb71'],['light','Classic Light','#dce8f5']];return `<div class="card-title"><h3>Appearance</h3><span>Personal to this account</span></div><div class="appearance-group"><h4>Theme</h4><div class="theme-list labeled">${themes.map(([name,label,color])=>`<button type="button" title="${label}" class="theme-chip ${s.theme===name?'active':''}" style="--swatch:${color}" onclick="setTheme('${name}')"><span>${label}</span></button>`).join('')}</div></div><div class="appearance-controls"><label>Text style<select onchange="updateAppearance('fontStyle',this.value)"><option value="modern" ${s.fontStyle==='modern'?'selected':''}>Modern — Inter + Poppins</option><option value="system" ${s.fontStyle==='system'?'selected':''}>System — Segoe UI</option><option value="editorial" ${s.fontStyle==='editorial'?'selected':''}>Editorial — Georgia</option></select></label><label>Interface text size<select onchange="updateAppearance('textScale',this.value)"><option value="compact" ${s.textScale==='compact'?'selected':''}>Compact</option><option value="normal" ${s.textScale==='normal'?'selected':''}>Comfortable</option><option value="large" ${s.textScale==='large'?'selected':''}>Large</option></select></label></div><p class="settings-note">The animated Nestlyra login scene is fixed for consistent branding. Add or remove your personal photo from Profile & account.</p>`}

  // Drive access is intentionally disabled until the Nestlyra Google OAuth app is verified.
  // Standard Google sign-in continues through app.js using basic identity scopes only.
  window.openDrivePdfPicker=()=>toast('Google Drive PDF storage is coming soon');

  const GROUP_MODULES=['overall',...Object.keys(MODULE_META).filter(x=>!['calendar','notes'].includes(x))];
  function groupConfig(groupId){const cloud=typeof groupState!=='undefined'?groupState.groups.find(x=>x.group_id===groupId)?.share_config:null,local=state.settings?.groupShareConfigs?.[groupId];return {...{modules:GROUP_MODULES,fields:['progress','counts','study','mock','activity'],records:['task','goal','plan','note']},...(cloud||local||{})}}
  window.groupSharingModal=()=>{if(typeof groupState==='undefined'||!groupState.selectedId)return toast('Open a group first');const config=groupConfig(groupState.selectedId);modal(`<div class="group-share-manager"><span class="eyebrow">SHARED RECORDS CONTROL</span><h2>Choose exactly what this group receives</h2><p>Turning a switch off stops future publication or hides that shared-record tool. Private titles, notes, files, applications and documents never enter aggregate progress.</p><nav class="group-share-tabs"><button class="active" data-share-tab="modules">Sections</button><button data-share-tab="fields">Data fields</button><button data-share-tab="records">Shared records</button></nav><div class="group-share-pages"><section data-share-page="modules">${GROUP_MODULES.map(id=>`<label><span><b>${id==='overall'?'◎':MODULE_META[id]?.[1]||'•'} ${h(id==='overall'?'Overall summary':MODULE_META[id]?.[0]||id)}</b><small>Aggregate only</small></span><input type="checkbox" data-share-option="modules" value="${id}" ${config.modules.includes(id)?'checked':''}></label>`).join('')}</section><section data-share-page="fields" class="hidden">${[['progress','Progress percentage'],['counts','Completed / total counts'],['study','Focused study minutes'],['mock','Mock-test average'],['activity','Active time, screen changes and presence']].map(([id,label])=>`<label><span><b>${h(label)}</b><small>${id==='activity'?'Requires activity sharing to be enabled':'No raw record names'}</small></span><input type="checkbox" data-share-option="fields" value="${id}" ${config.fields.includes(id)?'checked':''}></label>`).join('')}</section><section data-share-page="records" class="hidden">${[['task','Shared tasks'],['goal','Shared goals'],['plan','Shared plans'],['note','Short shared notes']].map(([id,label])=>`<label><span><b>${label}</b><small>Explicit co-edit record, separate from personal data</small></span><input type="checkbox" data-share-option="records" value="${id}" ${config.records.includes(id)?'checked':''}></label>`).join('')}</section></div><div class="modal-actions"><button class="btn ghost">Cancel</button><button type="button" class="btn primary" onclick="saveGroupSharingV37()">Save sharing choices</button></div></div>`);document.querySelectorAll('[data-share-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-share-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-share-page]').forEach(x=>x.classList.toggle('hidden',x.dataset.sharePage!==button.dataset.shareTab))})};
  window.saveGroupSharingV37=async()=>{const id=groupState.selectedId,config={};['modules','fields','records'].forEach(key=>config[key]=[...document.querySelectorAll(`[data-share-option="${key}"]:checked`)].map(x=>x.value));state.settings.groupShareConfigs=state.settings.groupShareConfigs||{};state.settings.groupShareConfigs[id]=config;save();if(sb&&cloudUser){const {error}=await sb.rpc('group_update_share_config',{p_group_id:id,p_config:config});if(error&&!/could not find|schema cache|does not exist/i.test(error.message))return toast(error.message)}closeModal();render();groupPublishProgress?.(true);toast('Sharing choices saved')};
  function groupRows(){return activeModules().map(moduleMetric).map(m=>({module_type:m.id,completed_count:m.complete,total_count:m.total,progress_percent:m.progress,study_minutes:m.id==='timer'?(state.activity||[]).reduce((s,x)=>s+Number(x.minutes||0),0):0,mock_average:m.id==='mocks'?m.progress:0,active_minutes:Math.round(Number(activityDay?.()?.activeMs||0)/60000),screen_changes:Number(activityDay?.()?.viewChanges||0),last_seen:new Date().toISOString()}))}

  function injectGroupShareControls(){if(viewName!=='groups'||typeof groupState==='undefined'||!groupState.selectedId)return;const actions=document.querySelector('.group-detail-head>div:last-child');if(actions&&!actions.querySelector('.group-sharing-button'))actions.insertAdjacentHTML('afterbegin','<button class="btn ghost group-sharing-button" onclick="groupSharingModal()">⚙ Shared data</button>');const config=groupConfig(groupState.selectedId);document.querySelectorAll('.group-shared-actions button').forEach(button=>{const type=(button.textContent.match(/task|goal|plan|note/i)||[])[0]?.toLowerCase();button.classList.toggle('hidden',Boolean(type&&!config.records.includes(type)))});document.querySelectorAll('.group-record-list article').forEach(row=>{const type=(row.querySelector('[onclick*="groupSharedModal"]')?.getAttribute('onclick')?.match(/\('(task|goal|plan|note)'/)||[])[1];row.classList.toggle('hidden',Boolean(type&&!config.records.includes(type)))})}

  function sectionPulse(){
    if(document.querySelector('.v37-section-pulse')||ENTITY[viewName]||['dashboard','settings','help','groups','messages','calendar','timer'].includes(viewName))return;
    let values=[];if(viewName==='subjects'){const t=allTopics();values=[['Topics',t.length],['Complete',t.filter(x=>x.status==='completed').length],['Overdue',t.filter(x=>x.due&&x.due<today()&&x.status!=='completed').length]]}else if(viewName==='tasks'){const t=state.tasks||[];values=[['All tasks',t.length],['Complete',t.filter(x=>x.status==='completed').length],['Overdue',t.filter(x=>x.due&&x.due<today()&&x.status!=='completed').length]]}else if(viewName==='notes'){values=[['Notes',(state.notes||[]).length],['With content',(state.notes||[]).filter(x=>x.content?.trim()).length],['Updated today',(state.notes||[]).filter(x=>x.updated===today()).length]]}else if(viewName==='jobs'){const j=state.jobApplications||[];values=[['Applications',j.length],['Interviews',j.filter(x=>x.status==='Interview').length],['Offers',j.filter(x=>['Offer','Selected'].includes(x.status)).length]]}if(!values.length)return;document.querySelector('.page-head')?.insertAdjacentHTML('afterend',`<div class="v37-section-pulse">${values.map(([a,b])=>`<span><small>${h(a)}</small><b>${h(b)}</b></span>`).join('')}</div>`)}

  function setDollState(mode){const stage=document.querySelector('.doll-stage');if(!stage)return;stage.dataset.dollState=mode;const copy={point:['Following your focus','Move anywhere—we will follow.'],watch:['You’re typing…','Shh… we’re watching your progress.'],idle:['Privacy mode','We look away when you pause.']}[mode];document.querySelector('#dollStateTitle').textContent=copy[0];document.querySelector('#dollStateText').textContent=copy[1]}
  function setupAnimatedLogin(){if(document.querySelector('#liveDollStack'))return;const password=document.querySelector('#loginPin'),stage=document.querySelector('.doll-stage');if(!password||!stage)return;let idleTimer;document.addEventListener('pointermove',event=>{const rect=stage.getBoundingClientRect(),x=event.clientX-(rect.left+rect.width/2),y=event.clientY-(rect.top+rect.height/2);stage.style.setProperty('--doll-x',`${Math.max(-10,Math.min(10,x/45))}px`);stage.style.setProperty('--doll-y',`${Math.max(-7,Math.min(7,y/65))}px`);stage.style.setProperty('--doll-turn',x<0?'-1':'1');if(document.activeElement!==password)setDollState('point')},{passive:true});const typing=()=>{clearTimeout(idleTimer);setDollState('watch');idleTimer=setTimeout(()=>setDollState('idle'),1300)};password.addEventListener('focus',typing);password.addEventListener('input',typing);password.addEventListener('blur',()=>setTimeout(()=>setDollState('point'),180));setDollState('idle')}

  const walkthroughSteps=[['Welcome to Nestlyra Focus','This quick tour shows the essentials. You can skip now or restart it from Manual & FAQ.','.brand'],['Choose your workspace tools','The left navigation contains only modules enabled for this workspace. Every ? opens that section’s manual.','.sidebar nav'],['One-screen command center','Dashboard graphs automatically summarize only the modules you enabled.','#view'],['Plan anything quickly','Use Quick add for a task, or open Calendar for Day, Week and Month planning.','#quickAdd'],['Your controls and photo','Open the upper-right profile button for Settings, appearance, modules, Groups and account controls.','#avatar']];let walkIndex=0;
  function clearWalkthrough(){document.querySelector('#nestlyraWalkthrough')?.remove();document.querySelectorAll('.walk-highlight').forEach(x=>x.classList.remove('walk-highlight'));document.body.classList.remove('walkthrough-open')}
  window.startNestlyraWalkthrough=()=>{window.nestlyraOnboardingActive=true;familyCancelBriefing?.();const dialog=document.querySelector('#modal');if(dialog?.open)dialog.close();walkIndex=0;requestAnimationFrame(paintWalkthrough)};
  function paintWalkthrough(){
    clearWalkthrough();window.nestlyraOnboardingActive=true;familyCancelBriefing?.();document.body.classList.add('walkthrough-open');
    const [title,body,selector]=walkthroughSteps[walkIndex],target=document.querySelector(selector),raw=target?.getBoundingClientRect();
    const pad=6,left=Math.max(pad,Math.min(innerWidth-pad,(raw?.left||innerWidth/2)-5)),top=Math.max(pad,Math.min(innerHeight-pad,(raw?.top||innerHeight/2)-5)),right=Math.max(left,Math.min(innerWidth-pad,(raw?.right||innerWidth/2)+5)),bottom=Math.max(top,Math.min(innerHeight-pad,(raw?.bottom||innerHeight/2)+5));
    const width=Math.max(1,right-left),height=Math.max(1,bottom-top),cardSide=left+width/2>innerWidth/2?'walk-card-left':'walk-card-right',cardLevel=top+height/2>innerHeight*.62?'walk-card-top':'walk-card-bottom';
    const shades=`<button type="button" class="walk-shade walk-shade-top" style="height:${top}px" aria-label="Skip walkthrough" onclick="finishNestlyraWalkthrough()"></button><button type="button" class="walk-shade walk-shade-left" style="top:${top}px;width:${left}px;height:${height}px" aria-label="Skip walkthrough" onclick="finishNestlyraWalkthrough()"></button><button type="button" class="walk-shade walk-shade-right" style="left:${right}px;top:${top}px;height:${height}px" aria-label="Skip walkthrough" onclick="finishNestlyraWalkthrough()"></button><button type="button" class="walk-shade walk-shade-bottom" style="top:${bottom}px" aria-label="Skip walkthrough" onclick="finishNestlyraWalkthrough()"></button>`;
    document.body.insertAdjacentHTML('beforeend',`<div id="nestlyraWalkthrough" class="walkthrough" role="dialog" aria-modal="true" aria-labelledby="walkthroughTitle">${shades}<i class="walk-focus-ring" style="left:${left}px;top:${top}px;width:${width}px;height:${height}px"></i><section class="walkthrough-card ${cardSide} ${cardLevel}"><button type="button" class="walkthrough-close" aria-label="Close walkthrough" onclick="finishNestlyraWalkthrough()">×</button><span>${walkIndex+1} / ${walkthroughSteps.length}</span><h2 id="walkthroughTitle">${h(title)}</h2><p>${h(body)}</p><div><button type="button" class="btn ghost" onclick="finishNestlyraWalkthrough()">Skip</button>${walkIndex?'<button type="button" class="btn ghost" onclick="previousWalkthrough()">Back</button>':''}<button type="button" class="btn primary" onclick="nextWalkthrough()">${walkIndex===walkthroughSteps.length-1?'Finish':'Next'}</button></div></section></div>`)
  }
  window.nextWalkthrough=()=>{if(walkIndex>=walkthroughSteps.length-1)return finishNestlyraWalkthrough();walkIndex++;paintWalkthrough()};
  window.previousWalkthrough=()=>{walkIndex=Math.max(0,walkIndex-1);paintWalkthrough()};
  window.finishNestlyraWalkthrough=()=>{try{state.settings=state.settings||{};state.settings.walkthroughCompleted=true;save()}finally{window.nestlyraOnboardingActive=false;clearWalkthrough();familyCancelBriefing?.()}};

  const baseDashboard=window.dashboard;window.dashboard=dashboardMarkup;
  const baseTimer=window.timerView;window.timerView=customTimerView;
  const baseAppearance=window.appearanceSettingsMarkup;window.appearanceSettingsMarkup=appearanceMarkup;
  const baseGroupSettings=window.groupSettingsCard;if(baseGroupSettings)window.groupSettingsCard=()=>baseGroupSettings().replace('<div class="modal-actions">','<div class="modal-actions"><button class="btn ghost" onclick="groupSharingModal()">Shared data controls</button>');
  const baseManualCard=window.familyManualSettingsCard;if(baseManualCard)window.familyManualSettingsCard=()=>baseManualCard().replace('<div class="modal-actions">','<div class="modal-actions"><button type="button" class="btn ghost" onclick="startNestlyraWalkthrough()">Start walkthrough</button>');
  const baseShowApp=window.showApp;window.showApp=()=>{const looksNew=(state.subjects||[]).length===1&&state.subjects[0]?.id==='sample-subject'&&!(state.tasks||[]).length&&!state.settings?.walkthroughCompleted;if(looksNew)window.nestlyraOnboardingActive=true;baseShowApp();updateAvatar();if(looksNew)setTimeout(startNestlyraWalkthrough,500)};
  const baseRender=window.render;window.render=()=>{baseRender();if(ENTITY[viewName]){view.innerHTML=richEntityView(viewName);view.classList.add('fit-view');view.dataset.currentView=viewName}if(viewName==='timer'){view.innerHTML=customTimerView();view.classList.add('fit-view')}updateAvatar();injectGroupShareControls();sectionPulse()};

  if(typeof groupPublishProgress==='function')window.groupPublishProgress=async(force=false)=>{if(!sb||!cloudUser||typeof groupState==='undefined'||groupState.schemaReady===false||(!force&&Date.now()-groupState.lastPublish<30000))return;groupState.lastPublish=Date.now();try{if(!groupState.groups.length){const {data,error}=await sb.rpc('group_list');if(error)return;groupState.groups=data||[]}for(const group of groupState.groups){const config=groupConfig(group.group_id),fields=new Set(config.fields||[]);if(group.share_progress===false&&group.share_activity===false)continue;for(const row of groupRows().filter(x=>(config.modules||[]).includes(x.module_type))){const payload={...row};if(group.share_progress===false||!fields.has('progress'))payload.progress_percent=0;if(group.share_progress===false||!fields.has('counts')){payload.completed_count=0;payload.total_count=0}if(group.share_progress===false||!fields.has('study'))payload.study_minutes=0;if(group.share_progress===false||!fields.has('mock'))payload.mock_average=0;if(group.share_activity===false||!fields.has('activity')){payload.active_minutes=0;payload.screen_changes=0;payload.last_seen=null}await sb.rpc('group_publish_snapshot',{p_group_id:group.group_id,p_snapshot:payload})}}}catch(error){console.warn('Group projection',error.message)}};

  document.addEventListener('DOMContentLoaded',()=>{
    setupAnimatedLogin();
    sessionStorage.removeItem('nestlyra.driveToken');
    document.querySelectorAll('.product-credit img,.parent-product-credit img').forEach(img=>{img.src='nestlyra-wordmark-gold.svg';img.alt='Nestlyra'});
    if(state.settings?.loginImage){delete state.settings.loginImage;delete state.settings.loginImagePosition;delete state.settings.loginImageShade;try{localStorage.removeItem('studyTracker.appearance.v1')}catch{}save()}
    updateAvatar();
  });
  addEventListener('keydown',event=>{if(event.key==='Escape'&&document.querySelector('#nestlyraWalkthrough')){event.preventDefault();finishNestlyraWalkthrough()}});
  addEventListener('resize',()=>{if(window.nestlyraOnboardingActive&&document.querySelector('#nestlyraWalkthrough'))requestAnimationFrame(paintWalkthrough)});
  addEventListener('pageshow',()=>{if(!window.nestlyraOnboardingActive)clearWalkthrough()});
})();
