(()=>{
  if(window.__PAVENRO_FINANCE_UI_V9__) return;
  window.__PAVENRO_FINANCE_UI_V9__=true;

  const CURRENCY={INR:'₹',USD:'$',EUR:'€',GBP:'£',AED:'د.إ',CNY:'¥',JPY:'¥',RUB:'₽',CAD:'C$',AUD:'A$',SGD:'S$',CHF:'CHF'};
  const ICONS={Dashboard:'⌂',Accounts:'▣',Transactions:'⇄',Bills:'▤',Budget:'◔',Income:'↗','Funds & Goals':'◎',Documents:'□',Calendar:'▦',Subscriptions:'◉',Debt:'◇','Net Worth':'↗',Investments:'◆',Reports:'▤',Notes:'✎','Tax Records':'▧',Paydays:'◷',Groups:'◎',Settings:'⚙','Help & Support':'?'};

  const style=document.createElement('style');
  style.id='pv-finance-ui-v9-style';
  style.textContent=`
    :root{--pv-side-wide:226px;--pv-side-rail:58px;--pv-brand-h:60px}
    .app{transition:grid-template-columns .18s ease!important}
    body:not(.pv-sidebar-rail) .app{grid-template-columns:var(--pv-side-wide) minmax(0,1fr)!important}
    body.pv-sidebar-rail .app{grid-template-columns:var(--pv-side-rail) minmax(0,1fr)!important}
    .sidebar{position:relative!important;overflow:visible!important;background:var(--sidebar,#123f2b)!important}
    .sidebar .brand{position:fixed!important;left:0!important;top:0!important;z-index:180!important;width:var(--pv-side-wide)!important;height:var(--pv-brand-h)!important;min-height:var(--pv-brand-h)!important;padding:0 10px!important;margin:0!important;display:flex!important;align-items:center!important;gap:6px!important;background:var(--sidebar,#123f2b)!important;border:0!important;box-shadow:none!important;transition:width .18s ease!important}
    .sidebar .brand img{width:95px!important;max-width:95px!important;height:auto!important;object-fit:contain!important;filter:brightness(0) invert(1)!important;opacity:1!important;flex:0 0 auto!important}
    .sidebar .brand small{font-size:8.5px!important;line-height:1!important;letter-spacing:.13em!important;font-weight:900!important;color:#fff!important;white-space:nowrap!important;opacity:.95!important}
    .pv-brand-separator{font-size:14px;color:rgba(255,255,255,.42);line-height:1}.pv-mini-mark{display:none;width:34px;height:34px;border-radius:9px;place-items:center;background:rgba(255,255,255,.07);color:#fff;font:800 17px/1 Inter,system-ui}
    .pv-brand-actions{margin-left:auto;display:flex;align-items:center}.pv-panel-toggle{width:30px;height:30px;border:0!important;background:transparent!important;color:#fff!important;border-radius:8px;display:grid;place-items:center;cursor:pointer;opacity:.82;padding:0}.pv-panel-toggle:hover{background:rgba(255,255,255,.07)!important;opacity:1}
    .pv-panel-icon{width:16px;height:14px;border:1.6px solid currentColor;border-radius:4px;display:block;position:relative}.pv-panel-icon:before{content:'';position:absolute;top:0;bottom:0;left:5px;width:1.5px;background:currentColor;opacity:.8}
    #pvSidebarBody{position:fixed!important;left:0!important;top:var(--pv-brand-h)!important;bottom:0!important;z-index:150!important;width:var(--pv-side-wide)!important;padding:6px 10px 10px!important;display:flex!important;flex-direction:column!important;background:var(--sidebar,#123f2b)!important;color:var(--sideText,#fff)!important;overflow-y:auto!important;overflow-x:hidden!important;transition:width .18s ease,padding .18s ease!important;scrollbar-width:none!important}#pvSidebarBody::-webkit-scrollbar{width:0!important;height:0!important}
    .pv-side-search{width:100%;height:38px;border:0!important;background:transparent!important;color:var(--sideText,#fff)!important;border-radius:9px;display:flex;align-items:center;gap:11px;padding:0 10px;cursor:pointer;font-size:12px;font-weight:600;opacity:.86;margin-bottom:4px}.pv-side-search:hover{background:rgba(255,255,255,.05)!important;opacity:1}.pv-side-search .pv-search-ico{width:18px;text-align:center;font-size:16px;flex:0 0 18px}
    #pvSidebarBody .nav-row{grid-template-columns:minmax(0,1fr) 23px!important;gap:2px!important;align-items:center!important}
    #pvSidebarBody .nav-btn,#pvSidebarBody .utility-btn,#pvSidebarBody #moreSections{min-height:36px!important;border:0!important;outline:0!important;box-shadow:none!important;background:transparent!important;border-radius:9px!important;color:var(--sideText,#fff)!important;padding:0 9px!important;margin:0!important;transition:background .14s ease,opacity .14s ease!important}
    #pvSidebarBody .nav-btn:hover,#pvSidebarBody .utility-btn:hover,#pvSidebarBody #moreSections:hover{background:rgba(255,255,255,.045)!important}#pvSidebarBody .nav-btn.active{background:rgba(255,255,255,.07)!important;box-shadow:inset 2px 0 0 rgba(255,255,255,.32)!important}
    #pvSidebarBody .help-btn{width:23px!important;height:26px!important;border:0!important;outline:0!important;background:transparent!important;box-shadow:none!important;color:var(--sideText,#fff)!important;border-radius:0!important;padding:0!important;font-size:11px!important;opacity:.24!important;transition:opacity .14s ease!important}#pvSidebarBody .nav-row:hover .help-btn,#pvSidebarBody .nav-btn.active+.help-btn{opacity:.52!important}#pvSidebarBody .help-btn:hover{opacity:.82!important;background:transparent!important}
    #pvSidebarBody .section-label{opacity:.38!important;font-size:8px!important;letter-spacing:.14em!important;margin:8px 9px 5px!important}#profileCard,.profile-card{display:none!important}
    body.pv-sidebar-rail .sidebar .brand{width:var(--pv-side-rail)!important;padding:0 12px!important;justify-content:center!important}body.pv-sidebar-rail .sidebar .brand img,body.pv-sidebar-rail .sidebar .brand small,body.pv-sidebar-rail .pv-brand-separator{display:none!important}body.pv-sidebar-rail .pv-mini-mark{display:grid!important}body.pv-sidebar-rail .pv-brand-actions{display:none!important}
    body.pv-sidebar-rail #pvSidebarBody{width:var(--pv-side-rail)!important;padding:6px 8px 10px!important;align-items:center!important}body.pv-sidebar-rail .pv-side-search{width:42px!important;justify-content:center!important;padding:0!important}body.pv-sidebar-rail .pv-side-search span:last-child{display:none!important}body.pv-sidebar-rail #pvSidebarBody .section-label,body.pv-sidebar-rail #pvSidebarBody .help-btn{display:none!important}body.pv-sidebar-rail #pvSidebarBody .nav-row{display:block!important;width:42px!important}
    body.pv-sidebar-rail #pvSidebarBody .nav-btn,body.pv-sidebar-rail #pvSidebarBody .utility-btn,body.pv-sidebar-rail #pvSidebarBody #moreSections{width:42px!important;min-width:42px!important;height:38px!important;min-height:38px!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:hidden!important}body.pv-sidebar-rail .pv-nav-label{display:none!important}body.pv-sidebar-rail .pv-nav-icon{display:inline-grid!important;place-items:center!important;width:20px!important;height:20px!important;margin:0!important;font-size:14px!important;flex:0 0 20px!important}body.pv-sidebar-rail #pvSidebarBody .divider{width:28px!important;margin:8px auto!important;opacity:.22!important}
    #pvRailExpandBtn{display:none;width:42px;height:38px;border:0;background:transparent;color:var(--sideText,#fff);border-radius:9px;place-items:center;cursor:pointer;margin:0 0 4px 0;opacity:.86}#pvRailExpandBtn:hover{background:rgba(255,255,255,.05);opacity:1}#pvRailExpandBtn .pv-panel-icon{width:16px;height:14px}body.pv-sidebar-rail #pvRailExpandBtn{display:grid!important}
    .page-head .eyebrow,.page .eyebrow,.workspace .eyebrow{display:none!important}.page-head{padding-top:0!important}
    #pvTopSection{display:flex;align-items:center;gap:9px;min-width:0;margin-right:auto}#pvTopSection .pv-currency-mark{width:34px;height:34px;border-radius:9px;background:var(--panel2,#eef3ed);color:var(--brand2,#2f7549);display:grid;place-items:center;font-weight:800;font-size:15px;flex:0 0 34px}#pvTopSection .pv-top-title{font-family:Georgia,serif;font-size:17px;font-weight:700;line-height:1.05;color:var(--ink,#17301f);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:230px}
    .topbar .searchbox,.topbar .global-search,.topbar input[type="search"]{max-width:420px}.workspace{padding-top:7px!important;padding-bottom:8px!important}.page{gap:7px!important}.dashboard-grid{gap:8px!important}.dash-bottom{min-height:122px!important;overflow:hidden!important}.dash-bottom>.card{min-height:0!important;overflow:hidden!important}.dash-bottom .card-body{min-height:0!important;overflow:hidden!important;padding:6px 8px!important}.dash-bottom .quick-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-template-rows:repeat(2,minmax(0,1fr))!important;height:100%!important;min-height:0!important;gap:6px!important}.dash-bottom .quick{min-height:0!important;height:100%!important;padding:3px 6px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important;overflow:hidden!important}
    html[dir="rtl"] #pvTopSection{direction:rtl}html[dir="rtl"] .pv-side-search{direction:rtl}@media(max-height:720px){.dash-bottom{min-height:108px!important}.workspace{padding-top:5px!important;padding-bottom:5px!important}}
  `;
  document.head.appendChild(style);

  const getCurrency=()=>{const sel=document.querySelector('#currencySelect, select[data-currency], .currency-select');const raw=(sel?.value || window.state?.settings?.currency || window.S?.s?.currency || 'INR').toUpperCase();return CURRENCY[raw] ? raw : 'INR'};
  const currentTitle=()=>{const h=document.querySelector('.page-head h1,.page h1,.workspace h1');if(h?.textContent.trim()) return h.textContent.trim();return window.state?.view || window.view || 'Finance Dashboard'};

  function normalizeNavButton(btn){if(!btn || btn.dataset.pvNavReady==='1') return;btn.dataset.pvNavReady='1';const label=(btn.dataset.v || btn.textContent || '').replace(/^[\s\S]*?([A-Za-z& ]+)$/,'$1').trim();const name=btn.dataset.v || label;const icon=ICONS[name] || '•';btn.innerHTML=`<span class="pv-nav-icon" aria-hidden="true">${icon}</span><span class="pv-nav-label"></span>`;btn.querySelector('.pv-nav-label').textContent=name;btn.title=name}

  function ensureSidebar(){
    const sidebar=document.querySelector('.sidebar');if(!sidebar) return false;const brand=sidebar.querySelector('.brand');if(!brand) return false;
    ['pvSideMenuBtn','pvSideMenu','pvSidebarCollapse','pvSidebarExpand','pvSideCollapse','pvSideExpand','pvRailExpand'].forEach(id=>document.getElementById(id)?.remove());brand.querySelectorAll('.pv-brand-actions,.pv-brand-separator,.pv-mini-mark').forEach(x=>x.remove());
    const img=brand.querySelector('img');if(img) img.alt='PAVENRO';let small=brand.querySelector('small');if(!small){small=document.createElement('small');brand.appendChild(small)}small.textContent='FINANCE';const sep=document.createElement('span');sep.className='pv-brand-separator';sep.textContent='|';brand.insertBefore(sep,small);const mini=document.createElement('span');mini.className='pv-mini-mark';mini.textContent='P';brand.insertBefore(mini,brand.firstChild);
    const actions=document.createElement('div');actions.className='pv-brand-actions';actions.innerHTML=`<button id="pvSideToggle" class="pv-panel-toggle" type="button" title="Collapse navigation" aria-label="Collapse navigation"><span class="pv-panel-icon" aria-hidden="true"></span></button>`;brand.appendChild(actions);
    let body=document.getElementById('pvSidebarBody');if(!body){body=document.createElement('div');body.id='pvSidebarBody';[...sidebar.children].filter(el=>el!==brand && el!==body).forEach(el=>body.appendChild(el));sidebar.appendChild(body)}
    [...body.querySelectorAll('.section-label')].forEach(el=>{if(/PAVENRO\s+FINANCE/i.test(el.textContent))el.remove()});body.querySelectorAll('.nav-btn,.utility-btn').forEach(normalizeNavButton);
    let expand=document.getElementById('pvRailExpandBtn');if(!expand){expand=document.createElement('button');expand.id='pvRailExpandBtn';expand.type='button';expand.title='Expand navigation';expand.setAttribute('aria-label','Expand navigation');expand.innerHTML='<span class="pv-panel-icon" aria-hidden="true"></span>';body.insertBefore(expand,body.firstChild)}
    let search=document.getElementById('pvSideSearch');if(!search){search=document.createElement('button');search.id='pvSideSearch';search.className='pv-side-search';search.type='button';search.innerHTML='<span class="pv-search-ico">⌕</span><span>Search</span>';body.insertBefore(search,expand.nextSibling)}
    const setRail=v=>{document.body.classList.toggle('pv-sidebar-rail',!!v);localStorage.setItem('pavenro.finance.sidebar.rail',v?'1':'0')};setRail(localStorage.getItem('pavenro.finance.sidebar.rail')==='1');document.getElementById('pvSideToggle').onclick=()=>setRail(true);expand.onclick=()=>setRail(false);search.onclick=()=>{const input=document.querySelector('.topbar input[type="search"],#globalSearch,.searchbox input,input[placeholder*="Search"],input[placeholder*="खोज"],input[placeholder*="搜索"]');if(input){input.focus();input.select?.()}};return true;
  }

  function ensureTopSection(){const top=document.querySelector('.topbar');if(!top)return;let holder=document.getElementById('pvTopSection');if(!holder){holder=document.createElement('div');holder.id='pvTopSection';holder.innerHTML='<div class="pv-currency-mark"></div><div class="pv-top-title"></div>';const search=top.querySelector('.searchbox,.global-search,input[type="search"]')?.closest('.searchbox,.global-search') || top.querySelector('input[type="search"]');if(search?.parentNode===top)top.insertBefore(holder,search);else top.insertBefore(holder,top.firstChild)}holder.querySelector('.pv-currency-mark').textContent=CURRENCY[getCurrency()];holder.querySelector('.pv-top-title').textContent=currentTitle()}
  function removeRepeatedBrandText(){document.querySelectorAll('.eyebrow').forEach(el=>{if(/PAVENRO|FINANCE/i.test(el.textContent))el.style.display='none'});document.querySelectorAll('.page-head,.workspace,.page').forEach(root=>{[...root.querySelectorAll('small,span,div')].forEach(el=>{if(el.children.length)return;const t=el.textContent.trim();if(/^PAVENRO\s*(FOCUS\s*[·|•-]\s*)?FINANCE$/i.test(t))el.style.display='none'})})}
  function apply(){ensureSidebar();ensureTopSection();removeRepeatedBrandText();document.querySelectorAll('#pvSidebarBody .help-btn').forEach(b=>{b.style.border='0';b.style.boxShadow='none';b.style.background='transparent'})}
  document.addEventListener('change',e=>{if(e.target.matches('#currencySelect,select[data-currency],.currency-select'))requestAnimationFrame(ensureTopSection)},true);
  let attempts=0;const boot=setInterval(()=>{attempts++;if(typeof window.render==='function'&&!window.render.__pvV9Wrapped){const base=window.render;const wrapped=function(...args){const out=base.apply(this,args);requestAnimationFrame(apply);return out};wrapped.__pvV9Wrapped=true;window.render=wrapped;clearInterval(boot);requestAnimationFrame(apply)}else if(attempts>160){clearInterval(boot);apply()}},50);
  let initial=0;const ready=setInterval(()=>{initial++;if(ensureSidebar()){clearInterval(ready);requestAnimationFrame(apply)}else if(initial>160)clearInterval(ready)},50);
})();
